CRF_GearScriptConfig {
 m_FactionName "NoShirts"
 m_FactionIcon "{0A1F947948102E69}CRF Images/opfor_nato.edds"
 m_Rifles {
  CRF_Weapon_Class "{62C61C1779B9F6CD}" {
   m_Weapon "{54C2B935F7C82441}Prefabs/Weapons/Rifles/AK74/LondonBathtub_AK74_Bayonet.et"
  }
 }
 m_bEnableLeadershipBinoculars 0
 m_bEnableAssistantBinoculars 0
}