CRF_GearScriptConfig {
 m_FactionName "Shirts"
 m_FactionIcon "{E5DECCCA6F4B7416}UI/Images/GS_Factions/BLUFOR_NATO.edds"
 m_Rifles {
  CRF_Weapon_Class "{62C61C175D3AEE4E}" {
   m_Weapon "{CD0CEFF39B090D79}Prefabs/Weapons/Rifles/M16/Variants/LondonBathtub_M16_Bayonet.et"
  }
 }
 m_DefaultClothing {
  CRF_Clothing "{62C61C161D7825A6}" {
   m_iClothingType HEADGEAR
   m_ClothingPrefabs {
    "{DD565E2C7E00A5BB}Prefabs/Characters/HeadGear/Hat_FlatCap_01/Hat_FlatCap_01_blue.et"
    "{67662815EFF734DD}Prefabs/Characters/HeadGear/Hat_FlatCap_01/Hat_FlatCap_01_darkgrey.et"
    "{E97A86BB050ED6D1}Prefabs/Characters/HeadGear/Hat_FlatCap_01/Hat_FlatCap_01_blue_Dirty.et"
    "{F6F24096665C6279}Prefabs/Characters/HeadGear/Hat_FlatCap_01/Hat_FlatCap_01_darkgrey_Dirty.et"
    "{6FEB0D9130EC400E}Prefabs/Characters/HeadGear/Hat_FlatCap_01/Hat_FlatCap_01_lightgrey.et"
   }
  }
  CRF_Clothing "{62C61C161D7825A2}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{27162F1F6EE6581A}Prefabs/Characters/Uniforms/Jacket_Denim_01/Jacket_Denim_01_brownShirt.et"
    "{EB0D74A43F74B522}Prefabs/Characters/Uniforms/Jacket_Denim_01/Jacket_Denim_01_strippedShirt.et"
    "{23A15812C40D34C2}Prefabs/Characters/Uniforms/Jacket_Denim_01/Jacket_Denim_01_strippedShirt_dirty.et"
   }
  }
  CRF_Clothing "{62C61C161D7825AD}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{5A8C9A020BD7ABA6}Prefabs/Characters/Uniforms/Pants_Trousers_01/Pants_Trousers_01_DarkGrey.et"
    "{537FD11C135757AC}Prefabs/Characters/Uniforms/Pants_Trousers_01/Pants_Trousers_01_DarkGrey_Dirty.et"
    "{6925E6C63EBCF623}Prefabs/Characters/Uniforms/Pants_Trousers_01/Pants_Trousers_01_DarkBrown.et"
   }
  }
  CRF_Clothing "{62C61C161D7825A9}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{DAAFD15478BDE1C3}Prefabs/Characters/Footwear/CombatBoots_US_01.et"
   }
  }
 }
 m_bEnableLeadershipBinoculars 0
 m_bEnableAssistantBinoculars 0
}