SCR_MapLayersBase {
 m_aLayers {
  SCR_LayerConfiguration "{54D50001FDCE8F33}" {
   m_fContourDensity 5
   m_fMajorContourDensity 10
  }
  SCR_LayerConfiguration "{54D50001FDAC5B34}" {
   m_fContourDensity 5
   m_fMajorContourDensity 10
  }
  SCR_LayerConfiguration "{54D50001C2EE1562}" {
  }
 }
}