CRF_CharacterIdentity {
 m_VisualIdentityArray {
  CRF_Character_Visual_Identity "{6665482E75ED4A6F}" {
   m_Head "{D073DA592FC49971}Prefabs/Characters/Heads/Head_AsianHead_A3_01.et"
   m_Body "{5EE1CAC3D1D1AC46}Prefabs/Characters/Basebody/CharacterBasebody_Asian_03.et"
  }
  CRF_Character_Visual_Identity "{6665482E75ED4A62}" {
   m_Head "{BC27EEB99300165F}Prefabs/Characters/Heads/Head_AsianHead_A3_02.et"
   m_Body "{5EE1CAC3D1D1AC47}Prefabs/Characters/Basebody/CharacterBasebody_Asian_01.et"
  }
  CRF_Character_Visual_Identity "{6665482E75ED4B9F}" {
   m_Head "{59BBA2409FE58134}Prefabs/Characters/Heads/Head_AsianHead_A3_03.et"
   m_Body "{5EE1CAC3D1D1AC46}Prefabs/Characters/Basebody/CharacterBasebody_Asian_03.et"
  }
  CRF_Character_Visual_Identity "{6665482E75ED4B9D}" {
   m_Head "{648F8778EA890803}Prefabs/Characters/Heads/Head_AsianHead_A3_04.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{6665482E75ED4B9B}" {
   m_Head "{8113CB81E66C9F68}Prefabs/Characters/Heads/Head_AsianHead_A3_05.et"
   m_Body "{5EE1CAC3D1D1AC46}Prefabs/Characters/Basebody/CharacterBasebody_Asian_03.et"
  }
  CRF_Character_Visual_Identity "{6665482E75ED4B99}" {
   m_Head "{ED47FF615AA81046}Prefabs/Characters/Heads/Head_AsianHead_A3_06.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{6665482E6B508B6D}" {
   m_Head "{08DBB398564D872D}Prefabs/Characters/Heads/Head_AsianHead_A3_07.et"
   m_Body "{5EE1CAC3D1D1AC46}Prefabs/Characters/Basebody/CharacterBasebody_Asian_03.et"
  }
 }
 m_SoundIdentityArray {
  CRF_Character_Sound_Identity "{6665482E75ED4B93}" {
   m_VoiceID 101
  }
  CRF_Character_Sound_Identity "{6665482E75ED4B91}" {
   m_VoiceID 101
   m_VoicePitch 0.8
  }
  CRF_Character_Sound_Identity "{6665482E75ED4B8F}" {
   m_VoiceID 101
   m_VoicePitch -1
  }
  CRF_Character_Sound_Identity "{6665482E75ED4B8E}" {
   m_VoiceID 102
  }
  CRF_Character_Sound_Identity "{6665482E75ED4B8D}" {
   m_VoiceID 102
   m_VoicePitch 0.9
  }
  CRF_Character_Sound_Identity "{6665482E75ED4B8C}" {
   m_VoiceID 102
   m_VoicePitch -1
  }
 }
}