FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{646EFE2CFCD87AFF}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{E50A6C740029CDD4}Prefabs/Characters/Heads/Character_Head_Droid.et"
   Body "{A37327F6FBC88327}Prefabs/Characters/Basebody/Body_Droid.et"
  }
 }
 SoundIdentityArray {
  SoundIdentity "{6950BE066E655834}" {
   VoiceID 102
   VoicePitch -900
  }
 }
 SocialIdentity SocialIdentity "{6950BE066E65580E}" {
  NamesConfig {
   "Was"
  }
  AliasesConfig {
   "1337llama"
   "Arkangel"
   "Whale"
   "Baron"
   "Battlebeav"
   "Cal"
   "Carcool12"
   "CollectiveS"
   "Collige"
   "Dagger"
   "Delfer"
   "DV"
   "Embrodak"
   "Flora"
   "Frans"
   "Geek-x"
   "Kaltag"
   "Gummi"
   "JLaw"
   "Johnstipation"
   "Kenji"
   "Lazz"
   "LookitsDante"
   "Master T 117"
   "Njpatman"
   "Nufflicks"
   "Philbilly"
   "PI23263"
   "Hawk"
   "RandAlThor"
   "Reckless"
   "Salami"
   "Shimavitz"
   "SkurtBird"
   "Slendersnipes"
   "Sonia"
   "Svir"
   "StalinForPresident"
   "Tanaka"
   "Techniker"
   "The Canadian"
   "TheCrazyCanuck"
   "Topher"
   "Uncle_Gavin"
   "Schmidtstorm"
   "Vampyrcat"
   "Votra"
   "Wandering_Blade"
  }
  SurnamesConfig {
   "a Droid"
  }
 }
}