CRF_CharacterIdentity {
 m_VisualIdentityArray {
  CRF_Character_Visual_Identity "{6952EDCE17CFA0A2}" {
   m_Head "{E50A6C740029CDD4}Prefabs/Characters/Heads/Character_Head_Droid.et"
   m_Body "{A37327F6FBC88327}Prefabs/Characters/Basebody/Body_Droid.et"
  }
 }
 m_SoundIdentityArray {
  CRF_Character_Sound_Identity "{6952EDCE178F9533}" {
   m_VoiceID 102
   m_VoicePitch -50
  }
 }
}