CRF_GearScriptConfig {
 m_FactionName "VIP/HVT"
 m_FactionIcon "{C8565602E0F422C5}Images/UI/Zeus GearScript Factions/CIV_NATO.edds"
 m_FactionWeapons CRF_Weapons "{665E12A677FD6898}" {
 }
 m_DefaultFactionGear CRF_Default_Gear "{665E12A677FD68B5}" {
  m_sLeadershipBinocularsPrefab "{243948B23D90BECB}Prefabs/Items/Equipment/Binoculars/Binoculars_B8/Binoculars_B8.et"
  m_sAssistantBinocularsPrefab "{243948B23D90BECB}Prefabs/Items/Equipment/Binoculars/Binoculars_B8/Binoculars_B8.et"
  m_DefaultMedicMedicalItems {
   CRF_Inventory_Item "{665E12A677FD68BD}" {
    m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
    m_iItemCount 10
   }
   CRF_Inventory_Item "{665E12A677FD68B8}" {
    m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
    m_iItemCount 3
   }
   CRF_Inventory_Item "{665E12A677FD6845}" {
    m_sItemPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
    m_iItemCount 6
   }
   CRF_Inventory_Item "{665E12A677FD6840}" {
    m_sItemPrefab "{5B2FD067D70C1E8F}Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et"
    m_iItemCount 6
   }
   CRF_Inventory_Item "{665E12A677FD684F}" {
    m_sItemPrefab "{527D7C5D2E476BDC}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_01.et"
    m_iItemCount 5
   }
   CRF_Inventory_Item "{665E12A677FD6849}" {
    m_sItemPrefab "{21EF98BFC1EB3793}Prefabs/Items/Equipment/Kits/MedicalKit_01/MedicalKit_01_USSR.et"
    m_iItemCount 1
   }
  }
  m_DefaultClothing {
   CRF_Clothing "{665E12A677FD6854}" {
    m_iClothingType BACKPACK
    m_ClothingPrefabs {
     "{CE832B86D234AD62}Prefabs/Items/Equipment/Backpacks/CRF_Backpack_Invisable.et"
    }
   }
   CRF_Clothing "{665E12A677FD6852}" {
    m_iClothingType HEADGEAR
    m_ClothingPrefabs {
     "{554D761A11D3D7EC}Prefabs/Characters/HeadGear/Hat_TruckerCap_01/Hat_TruckerCap_01_sawmillregina.et"
    }
   }
   CRF_Clothing "{665E12A677FD6860}" {
    m_iClothingType SHIRT
    m_ClothingPrefabs {
     "{27162F1F6EE6581A}Prefabs/Characters/Uniforms/Jacket_Denim_01/Jacket_Denim_01_brownShirt.et"
    }
   }
   CRF_Clothing "{665E12A677FD686B}" {
    m_iClothingType PANTS
    m_ClothingPrefabs {
     "{537FD11C135757AC}Prefabs/Characters/Uniforms/Pants_Trousers_01/Pants_Trousers_01_DarkGrey_Dirty.et"
    }
   }
   CRF_Clothing "{665E12A677FD6874}" {
    m_iClothingType BOOTS
    m_ClothingPrefabs {
     "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
     "{4C6029AB8BF5C044}Prefabs/Characters/Footwear/CombatBoots_Soviet_01_Dirty.et"
    }
   }
  }
  m_DefaultInventoryItems {
   CRF_Inventory_Item "{665E12A677FD6805}" {
    m_sItemPrefab "{7CEF68E2BC68CE71}Prefabs/Items/Equipment/Compass/Compass_Adrianov.et"
    m_iItemCount 1
   }
   CRF_Inventory_Item "{665E12A677FD680C}" {
    m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
    m_iItemCount 2
   }
   CRF_Inventory_Item "{665E12A677FD680E}" {
    m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
    m_iItemCount 1
   }
   CRF_Inventory_Item "{665E12A677FD6808}" {
    m_sItemPrefab "{E7FF723379730BD5}Prefabs/Items/PersonalBelongings/PersonalBelongings_CIV.et"
    m_iItemCount 0
   }
  }
 }
 m_CustomFactionGear CRF_Custom_Gear "{665E12A9078402D5}" {
  m_RolesToSetCustomGear {
   CRF_Role_Custom_Gear "{665E12A9053FAA3C}" {
    m_Role COMPANY_COMMANDER
    m_sRoleName "HVT/VIP"
   }
  }
 }
}