CRF_GearScriptConfig {
 m_FactionName "CIV"
 m_FactionIcon "{C8565602E0F422C5}Images/UI/Zeus GearScript Factions/CIV_NATO.edds"
 m_FactionIdentity "{11CAD6C8909CE567}Configs/Identities/CRF_CharacterIdentity_European.conf"
 m_DefaultClothing {
  CRF_Clothing "{66C918FE8AC8BD4E}" {
   m_iClothingType BACKPACK
   m_ClothingPrefabs {
    "{CE832B86D234AD62}Prefabs/Items/Equipment/Backpacks/CRF_Backpack_Invisable.et"
   }
  }
  CRF_Clothing "{66C918FE8AC87917}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{702F013CB1492541}Prefabs/Characters/Uniforms/Jacket_Suit_01/Jacket_Suit_01_base.et"
   }
  }
  CRF_Clothing "{66C918FE8AC87916}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{1A65EADE4B08583E}Prefabs/Characters/Uniforms/Pants_Suit_01/Pants_Suit_01_black_V1.et"
   }
  }
  CRF_Clothing "{66C918FE8AC87915}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
    "{4C6029AB8BF5C044}Prefabs/Characters/Footwear/CombatBoots_Soviet_01_Dirty.et"
   }
  }
 }
 m_sLeadershipBinocularsPrefab "{243948B23D90BECB}Prefabs/Items/Equipment/Binoculars/Binoculars_B8/Binoculars_B8.et"
 m_sAssistantBinocularsPrefab "{243948B23D90BECB}Prefabs/Items/Equipment/Binoculars/Binoculars_B8/Binoculars_B8.et"
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{66C918FE8AC8790E}" {
   m_sItemPrefab "{7CEF68E2BC68CE71}Prefabs/Items/Equipment/Compass/Compass_Adrianov.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{66C918FE8AC8790D}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{66C918FE8AC9F28C}" {
   m_sItemPrefab "{E7FF723379730BD5}Prefabs/Items/PersonalBelongings/PersonalBelongings_CIV.et"
   m_iItemCount 0
  }
 }
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{673A732425148146}" {
   m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{673A7324253ECA09}" {
   m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   m_iItemCount 1
  }
 }
 m_MedicMedicalItems {
  CRF_Inventory_Item "{66C918FE8AC70E39}" {
   m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
   m_iItemCount 10
  }
  CRF_Inventory_Item "{66C918FE8AC70E3B}" {
   m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   m_iItemCount 3
  }
  CRF_Inventory_Item "{66C918FE8AC8BEB3}" {
   m_sItemPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{66C918FE8AC8BD4D}" {
   m_sItemPrefab "{5B2FD067D70C1E8F}Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{66C918FE8AC8BD4C}" {
   m_sItemPrefab "{527D7C5D2E476BDC}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_01.et"
   m_iItemCount 5
  }
  CRF_Inventory_Item "{66C918FE8AC8BD4F}" {
   m_sItemPrefab "{21EF98BFC1EB3793}Prefabs/Items/Equipment/Kits/MedicalKit_01/MedicalKit_01_USSR.et"
   m_iItemCount 1
  }
 }
}