CRF_GearScriptConfig : "{2C00703A961BD7C4}Configs/Gearscripts/Standard/Vietnam/CRF_GS_PAVN.conf" {
 m_CustomFactionGear CRF_Custom_Gear "{66356ECFCDF50D65}" {
  m_RolesToSetCustomGear {
   CRF_Role_Custom_Gear "{66356ECFCDF50E1C}" {
    m_AdditionalInventoryItems {
     CRF_Inventory_Item "{66356ECFCDF50E0E}" {
      m_sItemPrefab "{4E2DA37BD38AF5E6}Prefabs/Weapons/Explosives/Explosive_Satchels/Throwable/OPFOR_Throwable_Satchel.et"
     }
    }
   }
  }
 }
}