CRF_GearScriptConfig : "{2C00703A961BD7C4}Configs/Gearscripts/Standard/Obsolete/Vietnam/CRF_GS_PAVN.conf" {
 m_FactionIdentity "{E13982CDA81E8F0C}Configs/Identities/CRF_CharacterIdentity_Asian.conf"
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{673A7322009E982B}" {
   m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{673A732200BA5C02}" {
   m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   m_iItemCount 1
  }
 }
 m_RolesToSetCustomSettings {
  CRF_Role_Custom_Gear "{66356ECFCDF50E1C}" {
   m_AdditionalInventoryItems {
    CRF_Inventory_Item "{66356ECFCDF50E0E}" {
     m_sItemPrefab "{4E2DA37BD38AF5E6}Prefabs/Weapons/Explosives/Explosive_Satchels/Throwable/OPFOR_Throwable_Satchel.et"
    }
   }
  }
 }
}