CRF_GearScriptConfig {
 m_FactionName "USSR"
 m_FactionIcon "{40B12B0DF911B856}UI/Textures/Editor/EditableEntities/Factions/EditableEntity_Faction_USSR.edds"
 m_FactionIdentity "{B96582A978CDF7AD}Configs/Identities/CRF_CharacterIdentity_Russian.conf"
 m_DefaultClothing {
  CRF_Clothing "{68531C9E5ABEDFBA}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{9F546CCA2582D16F}Prefabs/Characters/Uniforms/Jacket_M88.et"
    "{D262D2102B9931C6}Prefabs/Characters/Uniforms/Jacket_M88_rolledup.et"
   }
  }
  CRF_Clothing "{68531C9E5ABEDFA6}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{DCF980831E880F6A}Prefabs/Characters/Uniforms/Pants_M88.et"
   }
  }
  CRF_Clothing "{68531C9E5ABEDFA7}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
    "{4C6029AB8BF5C044}Prefabs/Characters/Footwear/CombatBoots_Soviet_01_Dirty.et"
   }
  }
  CRF_Clothing "{68535B27E05B95C1}" {
   m_iClothingType BACKPACK
   m_ClothingPrefabs {
    "{23DA0939B0158024}Prefabs/Items/Equipment/Backpacks/Backpack_Kolobok_Parachute.et"
   }
  }
 }
 m_sLeadershipBinocularsPrefab "{F2539FA5706E51E4}Prefabs/Items/Equipment/Binoculars/Binoculars_B12/Binoculars_B12.et"
 m_sAssistantBinocularsPrefab "{F2539FA5706E51E4}Prefabs/Items/Equipment/Binoculars/Binoculars_B12/Binoculars_B12.et"
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{68531C9E5ABEDFA5}" {
   m_sItemPrefab "{575EA58E67448C2A}Prefabs/Items/Equipment/Flashlights/Flashlight_Soviet_01/Flashlight_Soviet_01.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{68531C9E5ABEDFAA}" {
   m_sItemPrefab "{7CEF68E2BC68CE71}Prefabs/Items/Equipment/Compass/Compass_Adrianov.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{68531C9E5ABEDFAB}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{68531C9E5ABEB951}" {
   m_sItemPrefab "{6E35D94130954509}Prefabs/Items/Equipment/Accessories/ETool_ALICE/ETool_ALICE_FreeRoamBuilding_Gadget.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{68531C9E5ABEB953}" {
   m_sItemPrefab "{42232FFE6E7AC415}Prefabs/Items/Core/Wirecutters/wirecutters.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{68531C9E5ABF4A6B}" {
   m_sItemPrefab "{CBF9B9942E07B6B8}Prefabs/Items/Equipment/Accessories/ZipCuffs/ACE_Captives_ZipCuffs.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{68531C9E5ABF4A6C}" {
   m_sItemPrefab "{E096C6BD45C87B63}Prefabs/Items/PersonalBelongings/PersonalBelongings_USSR.et"
   m_iItemCount 0
  }
 }
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{68593AD1AD8D3BD7}" {
   m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   m_iItemCount 1
  }
 }
}