ActionManager {
 Contexts {
  ActionContext GlobalContext {
   ActionRefs +{
    "CRF_ParachuteDeploy"
   }
  }
  ActionContext IngameContext {
   ActionRefs {
    "MenuOpen"
    "MenuOpenWB"
    "ShowScoreboard"
    "ShowGroupMenu"
    "InstantVote"
    "COA_ChatToggle"
    "COA_EditorToggle"
    "EditorPing"
    "EditorPingUnlimitedOnly"
    "TasksOpen"
    "HintDismiss"
    "HintToggle"
    "HintContext"
    "TasksShowHint"
    "CVON_ShowVoiceRangeSlider"
    "CVON_VoiceRangeUp"
    "CVON_VoiceRangeDown"
    "COA_ToggleSideReady"
    "COA_AdminForceReady"
    "COA_OpenLobby"
    "MenuOpen"
    "CSI_PlayerSettingsMenu"
    "CSI_RevealUI"
    "DisconnectDrone"
    "CRF_PropHuntTransform"
    "CRF_PropHuntNoise"
    "CRF_PropHuntNextNoise"
   }
  }
 }
}