SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  SCR_GarbageSystem "{5F10E7EA29B0EDEC}" {
   Rules {
    EntityClassGarbageRule "{60713063DB480AC7}" {
     PlayerDistance 30
    }
    EntityClassGarbageRule "{60713063F62751A3}" {
     OnlyDestroyed 1
    }
   }
  }
  GC_SuppressionSystem "{684E2A62F38CECCD}" {
   m_fRecoveryRate 0.4
  }
 }
}