ActionManager {
 Actions {
  Action CRF_ParachuteDeploy {
   InputSource InputSourceSum "{69F4F58E949CAF3D}" {
    Sources {
     InputSourceValue "{69F4F58E9260FC06}" {
      FilterPreset "click"
      Input "keyboard:KC_SPACE"
      Filter InputFilterDown "{69F4F58E81F472F1}" {
      }
     }
     InputSourceValue "{69F4F58E934A458D}" {
      FilterPreset "gamepad:click"
      Input "gamepad0:a"
      Filter InputFilterClick "{69F4F58EA6C5D9DF}" {
      }
     }
    }
   }
  }
  Action CRF_PropHuntTransform {
   InputSource InputSourceSum "{69F4F58EABD328B8}" {
    Sources {
     InputSourceValue "{69F4F58EDFD543B6}" {
      FilterPreset "click"
      Input "keyboard:KC_T"
      Filter InputFilterDown "{69F4F58EC66704D8}" {
      }
     }
    }
   }
  }
  Action CRF_PropHuntNoise {
   InputSource InputSourceSum "{69F4F58ED18481A5}" {
    Sources {
     InputSourceValue "{69F4F58EDF0116AF}" {
      FilterPreset "click"
      Input "keyboard:KC_B"
      Filter InputFilterDown "{69F4F58ECD3ACEF2}" {
      }
     }
    }
   }
  }
  Action CRF_PropHuntNextNoise {
   InputSource InputSourceSum "{69F4F58ED03F6665}" {
    Sources {
     InputSourceValue "{69F4F58EDE28069F}" {
      FilterPreset "click"
      Input "keyboard:KC_G"
      Filter InputFilterDown "{69F4F58EC990A2DD}" {
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext GlobalContext {
   ActionRefs +{
    "CRF_ParachuteDeploy"
   }
  }
  ActionContext IngameContext {
   ActionRefs {
    "MenuOpen"
    "MenuOpenWB"
    "ShowScoreboard"
    "ShowGroupMenu"
    "InstantVote"
    "ChatToggle"
    "EditorToggle"
    "EditorPing"
    "EditorPingUnlimitedOnly"
    "TasksOpen"
    "HintDismiss"
    "HintToggle"
    "HintContext"
    "TasksShowHint"
    "CVON_ShowVoiceRangeSlider"
    "CVON_VoiceRangeUp"
    "CVON_VoiceRangeDown"
    "COA_ToggleSideReady"
    "COA_AdminForceReady"
    "COA_OpenLobby"
    "MenuOpen"
    "CSI_PlayerSettingsMenu"
    "CSI_RevealUI"
    "DisconnectDrone"
    "CRF_PropHuntTransform"
    "CRF_PropHuntNoise"
    "CRF_PropHuntNextNoise"
   }
  }
 }
}