SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  GC_SuppressionSystem "{684E2A62F38CECCD}" {
   m_fFlinchShakeMultiplier 0.5
   m_fFlinchShakeSuppressedMultiplier 0.25
   m_fRecoveryDelay 4.5
   m_fRecoveryRate 0.4
  }
  SCR_PersistenceSystem "{68CEE4E49881A573}" {
   Enabled 0
   SystemLocation Server
   SystemPoints 0x2000 0x10
   Config "{5BA7C4643477E2D7}Configs/Systems/Persistence/EditableMission.conf"
  }
  CRF_GearscriptSystem "{68CEE4E57FE75D39}" {
   SystemLocation Server
   SystemPoints 0 0x10
  }
 }
}