SystemSettings : "{1C60D2EDA2B468B8}Configs/Systems/BaseGameModeSystems.conf" {
 Systems {
  GC_SuppressionSystem "{684E2A62F38CECCD}" {
   m_fRecoveryDelay 4.5
   m_fFlinchShakeMultiplier 0.5
   m_fFlinchShakeSuppressedMultiplier 0.25
  }
  SCR_PersistenceSystem "{65DC893A5A752E89}" {
   Enabled 1
  }
 }
}