SystemSettings : "{1C60D2EDA2B468B8}Configs/Systems/BaseGameModeSystems.conf" {
 Systems {
  GC_SuppressionSystem "{684E2A62F38CECCD}" {
   m_fFlinchShakeMultiplier 0.5
   m_fFlinchShakeSuppressedMultiplier 0.25
   m_fRecoveryDelay 4.5
  }
  SCR_PersistenceSystem "{65DC893A5A752E89}" {
   Enabled 1
   States {
    ScriptedStatePersistenceConfig {
     StateClass "CRF_GamemodeStateData"
     Serializer "CRF_GamemodeSerializer"
     m_eSaveMask 7
    }
    ScriptedStatePersistenceConfig {
     StateClass "CRF_SlottingManagerStateData"
     Serializer "CRF_SlottingManagerSerializer"
     m_eSaveMask 7
    }
    ScriptedStatePersistenceConfig {
     StateClass "CRF_RespawnManagerStateData"
     Serializer "CRF_RespawnManagerSerializer"
     m_eSaveMask 7
    }
    ScriptedStatePersistenceConfig {
     StateClass "CRF_GameTimerStateData"
     Serializer "CRF_GameTimerSerializer"
     m_eSaveMask 7
    }
    ScriptedStatePersistenceConfig {
     StateClass "CRF_SafestartStateData"
     Serializer "CRF_SafestartSerializer"
     m_eSaveMask 7
    }
    ScriptedStatePersistenceConfig {
     StateClass "CRF_FrontlineStateData"
     Serializer "CRF_FrontlineSerializer"
     m_eSaveMask 7
    }
    ScriptedStatePersistenceConfig {
     StateClass "CRF_InsurgencyStateData"
     Serializer "CRF_InsurgencySerializer"
     m_eSaveMask 7
    }
    ScriptedStatePersistenceConfig {
     StateClass "CRF_RushStateData"
     Serializer "CRF_RushSerializer"
     m_eSaveMask 7
    }
    ScriptedStatePersistenceConfig {
     StateClass "CRF_RaidStateData"
     Serializer "CRF_RaidSerializer"
     m_eSaveMask 7
    }
   }
  }
 }
}