CRF_GearScriptConfig : "{EC17EA82C390260C}Configs/Gearscripts/Standard/Modern/CRF_GS_RHSMSV.conf" {
  m_MMG CRF_Spec_Weapon_Class "{629D042A59FA7CC8}" {
   m_Weapon "{C7115ECCD10BF1FB}Prefabs/Weapons/MachineGuns/PKM/MG_PKM_AP.et"
   m_MagazineArray {
    CRF_Spec_Magazine_Class "{629D042A59FA7CCB}" {
     m_Magazine "{0110F6D92703114A}Prefabs/Weapons/Magazines/Box_762x54_PK_100rnd_7N13_4Ball_1Tracer.et"
     m_MagazineCount 7
     m_AssistantMagazineCount 8
    }
   }
  }
  m_AT CRF_Spec_Weapon_Class "{629D042A59FA7CCC}" {
   m_Weapon "{3FEEC75992196DAC}Prefabs/Weapons/Launchers/RPG18/Launcher_RPG18.et"
  }
 
  m_DefaultInventoryItems {
   CRF_Inventory_Item "{629D042DD805C276}" {
    m_iItemCount 2
   }
  }
  m_RolesToSetCustomSettings {
   CRF_Role_Custom_Gear "{650311B79D84A1B1}" {
    m_Role COMBAT_ENGINEER
    m_AdditionalInventoryItems {
     CRF_Inventory_Item "{64FF6026EE3951BA}" {
      m_sItemPrefab "{73F69547963CAEE0}PrefabsEditable/Explosives/E_DemoBlock_TSh400g.et"
      m_iItemCount 1
     }
     CRF_Inventory_Item "{64FF6026EE2F6214}" {
      m_sItemPrefab "{90976DC90A223095}Prefabs/Items/Equipment/Detonators/BlastingMachine_KPM_3U1/BlastingMachine_KPM_3U1.et"
      m_iItemCount 1
     }
     CRF_Inventory_Item "{64FF6026EE406EBB}" {
      m_sItemPrefab "{2E5BFBBBC0AD79CE}Prefabs/Weapons/Explosives/Explosive_Satchels/OPFOR_Satchel.et"
      m_iItemCount 3
     }
    }
   }
  }
}