CRF_GearScriptConfig {
 m_FactionName "Naked and Afraid"
 m_FactionIcon "{9B36CCF705735F7A}Assets/Characters/Heads/Head_White_04/Data/Head_White_04_BCR.edds"
 m_FactionWeapons CRF_Weapons "{64E62B658B1F818D}" {
  m_Rifle {
   CRF_Weapon_Class "{65452C78CA70998D}" {
    m_Weapon "{E998FA484B0C4BFF}Prefabs/Weapons/Handguns/Glock/Handgun_Glock17.et"
    m_MagazineArray {
     CRF_Magazine_Class "{64E62B666F9C55ED}" {
      m_Magazine "{F20D1122BC5CD9F2}Prefabs/Weapons/Magazines/glock_magazine/Magazine_9x19_Glock_17rnd.et"
      m_MagazineCount 25
     }
    }
   }
  }
  m_RifleUGL {
   CRF_Weapon_Class "{65452C78CA29C4EB}" {
    m_Weapon "{E998FA484B0C4BFF}Prefabs/Weapons/Handguns/Glock/Handgun_Glock17.et"
    m_MagazineArray {
     CRF_Magazine_Class "{64E62B666F9C55ED}" {
      m_Magazine "{F20D1122BC5CD9F2}Prefabs/Weapons/Magazines/glock_magazine/Magazine_9x19_Glock_17rnd.et"
      m_MagazineCount 25
     }
    }
   }
  }
  m_Carbine {
   CRF_Weapon_Class "{65452C78C49213FA}" {
    m_Weapon "{E998FA484B0C4BFF}Prefabs/Weapons/Handguns/Glock/Handgun_Glock17.et"
    m_MagazineArray {
     CRF_Magazine_Class "{64E62B666F9C55ED}" {
      m_Magazine "{F20D1122BC5CD9F2}Prefabs/Weapons/Magazines/glock_magazine/Magazine_9x19_Glock_17rnd.et"
      m_MagazineCount 25
     }
    }
   }
  }
  m_Pistol {
   CRF_Weapon_Class "{64E62B658B1F818B}" {
    m_Weapon "{E998FA484B0C4BFF}Prefabs/Weapons/Handguns/Glock/Handgun_Glock17.et"
    m_MagazineArray {
     CRF_Magazine_Class "{64E62B658B1F8197}" {
      m_Magazine "{F20D1122BC5CD9F2}Prefabs/Weapons/Magazines/glock_magazine/Magazine_9x19_Glock_17rnd.et"
      m_MagazineCount 25
     }
    }
   }
  }
 }
 m_DefaultFactionGear CRF_Default_Gear "{64E62B658B1F8198}" {
  m_bEnableLeadershipBinoculars 0
  m_bEnableAssistantBinoculars 0
  m_DefaultClothing {
   CRF_Clothing "{64E62B658B1F8199}" {
    m_iClothingType BACKPACK
    m_ClothingPrefabs {
     "{CE832B86D234AD62}Prefabs/Items/Equipment/Backpacks/CRF_Backpack_Invisable.et"
    }
   }
  }
  m_DefaultInventoryItems {
   CRF_Inventory_Item "{64E62B658B1F81F4}" {
    m_sItemPrefab "{3A421547BC29F679}Prefabs/Items/Equipment/Flashlights/Flashlight_MX991/Flashlight_MX991.et"
    m_iItemCount 1
   }
   CRF_Inventory_Item "{64E62B658B1F81F7}" {
    m_sItemPrefab "{9DB69176CEF0EE97}Prefabs/Weapons/Grenades/Smoke_ANM8HC.et"
    m_iItemCount 1
   }
   CRF_Inventory_Item "{64E62B658B1F81F3}" {
    m_sItemPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
    m_iItemCount 1
   }
   CRF_Inventory_Item "{64E62B658B1F81F9}" {
    m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/PaperMap_01_folded.et"
    m_iItemCount 1
   }
   CRF_Inventory_Item "{64E62B658B1F81CB}" {
    m_sItemPrefab "{78ED4FEF62BBA728}Prefabs/Items/Equipment/Watches/Watch_SandY184A.et"
    m_iItemCount 1
   }
   CRF_Inventory_Item "{64E62B658B1F81D6}" {
    m_sItemPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
    m_iItemCount 2
   }
   CRF_Inventory_Item "{64E62B658B1F81D1}" {
    m_sItemPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
    m_iItemCount 1
   }
   CRF_Inventory_Item "{64E62B658B1F81D3}" {
    m_sItemPrefab "{6E35D94130954509}Prefabs/Items/Equipment/Accessories/ETool_ALICE/ETool_ALICE_FreeRoamBuilding_Gadget.et"
    m_iItemCount 1
   }
  }
 }
 m_CustomFactionGear CRF_Custom_Gear "{64E62B658B1F81DE}" {
 }
}