CRF_GearScriptConfig {
 m_FactionName "\"Police\""
 m_FactionIcon "{D18D4D7FD75E949F}UI/Flag/Zimnitrita_Flag_128x128.edds"
 m_Pistols {
  CRF_Weapon_Class "{62C61C09F53DEF10}" {
   m_Weapon "{E998FA484B0C4BFF}Prefabs/Weapons/Handguns/Glock/Handgun_Glock17.et"
   m_MagazineArray {
    CRF_Magazine_Class "{62C61C09E321ADA8}" {
     m_Magazine "{F20D1122BC5CD9F2}Prefabs/Weapons/Magazines/glock_magazine/Magazine_9x19_Glock_17rnd.et"
     m_MagazineCount 25
    }
   }
  }
 }
 m_DefaultClothing {
  CRF_Clothing "{62C61C09CD709384}" {
   m_iClothingType BACKPACK
   m_ClothingPrefabs {
    "{CE832B86D234AD62}Prefabs/Items/Equipment/Backpacks/CRF_Backpack_Invisable.et"
   }
  }
  CRF_Clothing "{62C61C09CD709387}" {
   m_iClothingType HEADGEAR
   m_ClothingPrefabs {
    "{28185F0BFA3148BB}Prefabs/Characters/HeadGear/Hat_M70_01/Hat_M70_Police.et"
   }
  }
  CRF_Clothing "{62C61C09CD709382}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{66CBDE9E7F4D467B}Prefabs/Characters/Uniforms/Shirt_CottonShirt_01/Shirt_Police1.et"
   }
  }
  CRF_Clothing "{62C61C09CD70938D}" {
   m_iClothingType ARMOREDVEST
   m_ClothingPrefabs {
    "{5AF144E74C4B6F6B}Prefabs/Characters/Vests/Vest_NAZ/Vest_NAZ_Police1.et"
   }
  }
  CRF_Clothing "{62C61C09CD70938E}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{01A26630020FDBD9}Prefabs/Characters/Uniforms/Pants_M88_police.et"
   }
  }
  CRF_Clothing "{62C61C09CD709389}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{DAAFD15478BDE1C3}Prefabs/Characters/Footwear/CombatBoots_US_01.et"
   }
  }
 }
 m_bEnableLeadershipBinoculars 0
 m_bEnableAssistantBinoculars 0
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{62C61C09CD709078}" {
   m_sItemPrefab "{3A421547BC29F679}Prefabs/Items/Equipment/Flashlights/Flashlight_MX991/Flashlight_MX991.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C09CD709065}" {
   m_sItemPrefab "{9DB69176CEF0EE97}Prefabs/Weapons/Grenades/Smoke_ANM8HC.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C09CD709067}" {
   m_sItemPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C09CD709061}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C09CD709063}" {
   m_sItemPrefab "{78ED4FEF62BBA728}Prefabs/Items/Equipment/Watches/Watch_SandY184A.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C09CD70906D}" {
   m_sItemPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{62C61C09CD70906E}" {
   m_sItemPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C09CD709068}" {
   m_sItemPrefab "{6E35D94130954509}Prefabs/Items/Equipment/Accessories/ETool_ALICE/ETool_ALICE_FreeRoamBuilding_Gadget.et"
   m_iItemCount 1
  }
 }
}