CRF_SightArsenalConfig {
 m_aSights {
  "{8D4BAA235F7EDBEA}Prefabs/Weapons/Attachments/Optics/1p78/Optic_1P78.et"
  "{E35250A515F71A22}Prefabs/Weapons/Attachments/Optics/1p87/Optic_1P87_1P90.et"
  "{64A680729707DBFE}Prefabs/Weapons/Attachments/Optics/1p87/Optic_1P87_1PN138.et"
  "{4572378B75A039EC}Prefabs/Weapons/Attachments/Optics/1pn93/Optic_1PN93.et"
  "{969F74903AFFCABE}Prefabs/Weapons/Attachments/Optics/bravo4/Optic_bravo4.et"
  "{7D988DAC1E88AF14}Prefabs/Weapons/Attachments/Optics/bravo4/Optic_bravo4_tan.et"
  "{DA2AED4A5F958164}Prefabs/Weapons/Attachments/Optics/su230/Optic_SU230.et"
  "{7DB681643152613C}Prefabs/Weapons/Attachments/Optics/su230/Optic_SU230_MRDS.et"
  "{01BE30D243F57EE2}Prefabs/Weapons/Attachments/Optics/su230/Optic_SU230_MRDS_tan.et"
  "{7A5A21F5F2F508CA}Prefabs/Weapons/Attachments/Optics/su230/Optic_SU230_tan.et"
  "{2518CA6044D6BBDD}Prefabs/Weapons/Attachments/Optics/ta31rco/Optic_TA31RCO.et"
  "{90A20A1ED92AD477}Prefabs/Weapons/Attachments/Optics/ta31rco/Optic_TA31RCO_ARD.et"
  "{30B41A4172CBD098}Prefabs/Weapons/Attachments/Optics/ta31rco/Optic_TA31RCO_ARD_army.et"
  "{50475BC9E6A7ABD0}Prefabs/Weapons/Attachments/Optics/ta31rco/Optic_TA31RCO_army.et"
  "{36EF773EB236A891}Prefabs/Weapons/Attachments/Optics/ta648mdo/Optic_TA648MDO_rmr.et"
  "{6CC2AB2044189ED1}Prefabs/Weapons/Attachments/Optics/ta648mdo/Optic_TA648MDO_dummy.et"
 }
}