CRF_CharacterIdentity {
 m_VisualIdentityArray {
  CRF_Character_Visual_Identity "{689C59047588192B}" {
   m_Head "{F4016BBC1A1AB199}Prefabs/Characters/Heads/Head_Persian_01.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689C5904117A2459}" {
   m_Head "{9A4893348B1AB242}Prefabs/Characters/Heads/Head_Persian_01_camo.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689C590556ED7CBB}" {
   m_Head "{E2831DCA832A685C}Prefabs/Characters/Heads/Head_Persian_02.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689C59055088C510}" {
   m_Head "{9456D77CB6EDBD98}Prefabs/Characters/Heads/Head_Persian_02_camo.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689C59054CF63631}" {
   m_Head "{071F51338FCFFF37}Prefabs/Characters/Heads/Head_Persian_03.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689C590548F138F5}" {
   m_Head "{91A314BB5DBF472E}Prefabs/Characters/Heads/Head_Persian_03_camo.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689D189310EF459F}" {
   m_Head "{F8ED1678144C1013}Prefabs/Characters/Heads/Head_AfricanHead_h.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{689D1893F9E30377}" {
   m_Head "{151D478228758DF1}Prefabs/Characters/Heads/Head_AfricanHead_h_camo.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
 }
 m_SoundIdentityArray {
  CRF_Character_Sound_Identity "{689C5906C536966C}" {
   m_VoiceID 101
  }
  CRF_Character_Sound_Identity "{689C5906C536AD08}" {
   m_VoiceID 101
   m_VoicePitch 0.8
  }
  CRF_Character_Sound_Identity "{689C5906C536AD0A}" {
   m_VoiceID 101
   m_VoicePitch -1
  }
  CRF_Character_Sound_Identity "{689C5906C536AD05}" {
   m_VoiceID 102
  }
  CRF_Character_Sound_Identity "{689C5906C536AD04}" {
   m_VoiceID 102
   m_VoicePitch 0.9
  }
  CRF_Character_Sound_Identity "{689C5906C536AD07}" {
   m_VoiceID 102
   m_VoicePitch -1
  }
 }
}