CRF_CharacterIdentity {
 m_VisualIdentityArray {
  CRF_Character_Visual_Identity "{689D188B10D56460}" {
   m_Head "{F4016BBC1A1AB199}Prefabs/Characters/Heads/Head_Persian_01.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689D188B10D56477}" {
   m_Head "{E2831DCA832A685C}Prefabs/Characters/Heads/Head_Persian_02.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689D188B10DAE1A9}" {
   m_Head "{071F51338FCFFF37}Prefabs/Characters/Heads/Head_Persian_03.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689D189388D7FA51}" {
   m_Head "{F8ED1678144C1013}Prefabs/Characters/Heads/Head_AfricanHead_h.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{689D18907E74614E}" {
   m_Head "{04F4D8CBA36A534C}Prefabs/Characters/Heads/Head_AfricanHead_02.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
 }
 m_SoundIdentityArray {
  CRF_Character_Sound_Identity "{689D188B10DA90EE}" {
   m_VoiceID 101
  }
  CRF_Character_Sound_Identity "{689D188B10DA90ED}" {
   m_VoiceID 101
   m_VoicePitch 0.8
  }
  CRF_Character_Sound_Identity "{689D188B10DA90EC}" {
   m_VoiceID 101
   m_VoicePitch -1
  }
  CRF_Character_Sound_Identity "{689D188B10DAB413}" {
   m_VoiceID 102
  }
  CRF_Character_Sound_Identity "{689D188B10DAB41C}" {
   m_VoiceID 102
   m_VoicePitch 0.9
  }
  CRF_Character_Sound_Identity "{689D188B10DAB41D}" {
   m_VoiceID 102
   m_VoicePitch -1
  }
 }
}