CRF_CharacterIdentity {
 m_VisualIdentityArray {
  CRF_Character_Visual_Identity "{689D1890614E26EA}" {
   m_Head "{F4016BBC1A1AB199}Prefabs/Characters/Heads/Head_Persian_01.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689D1890614E26FD}" {
   m_Head "{E2831DCA832A685C}Prefabs/Characters/Heads/Head_Persian_02.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689D1890614E8E41}" {
   m_Head "{071F51338FCFFF37}Prefabs/Characters/Heads/Head_Persian_03.et"
   m_Body "{000A00972B3D8EF5}Prefabs/Characters/Basebody/CharacterBasebody_03.et"
  }
  CRF_Character_Visual_Identity "{689D1890614E8E47}" {
   m_Head "{F8ED1678144C1013}Prefabs/Characters/Heads/Head_AfricanHead_h.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
 }
 m_SoundIdentityArray {
  CRF_Character_Sound_Identity "{689D1890614EB53D}" {
   m_VoiceID 101
  }
  CRF_Character_Sound_Identity "{689D1890614EB53C}" {
   m_VoiceID 101
   m_VoicePitch 0.8
  }
  CRF_Character_Sound_Identity "{689D1890614EB503}" {
   m_VoiceID 101
   m_VoicePitch -1
  }
  CRF_Character_Sound_Identity "{689D1890614EB502}" {
   m_VoiceID 102
  }
  CRF_Character_Sound_Identity "{689D1890614EB501}" {
   m_VoiceID 102
   m_VoicePitch 0.9
  }
  CRF_Character_Sound_Identity "{689D1890614EB585}" {
   m_VoiceID 102
   m_VoicePitch -1
  }
 }
}