CRF_GearScriptConfig : "{4B989C4FB6562899}Configs/Gearscripts/Standard/Modern/CRF_GS_RHSUSMC.conf" {
 m_FactionName "CDF"
 m_FactionIcon "{2E9959A922B7CE3E}Prefabs/Assets/Props/Fabric/Data/CDF_Flags/EditableEntitie_Faction_CDF.edds"
 m_DefaultFactionGear CRF_Default_Gear "{629F78CE67CB3C00}" {
  m_DefaultClothing {
   CRF_Clothing "{629F78CE67CB3C24}" {
    m_ClothingPrefabs {
     "{74B0180D7A230B9F}Prefabs/Characters/HeadGear/Helmet_Spartan3/CRF_Helmet_Spartan3_OD_Peltor.et"
     "{8BF125BFD239156D}Prefabs/Characters/HeadGear/Helmet_Spartan3/CRF_Helmet_Spartan3_OD_Sordin.et"
    }
   }
   CRF_Clothing "{629F78CE67CB3C3D}" {
    m_ClothingPrefabs {
     "{9F546CCA2582D170}Prefabs/Prefabs/Characters/Uniforms/Jacket_M88/Jacket_M88_CDF.et"
     "{5A85DFF5972E4CA1}Prefabs/Prefabs/Characters/Uniforms/Jacket_M88/Jacket_M88_CDF_Rolledup.et"
    }
   }
   CRF_Clothing "{629F78CE67CB3C34}" {
    m_ClothingPrefabs {
     "{7028D46E1F6044BF}Prefabs/Characters/Vests/Vest_TV110/Vest_TV110_OD.et"
    }
   }
   CRF_Clothing "{629F78CE67CB3C37}" {
    m_ClothingPrefabs {
     "{BEE14F0613F452EF}Prefabs/Prefabs/Characters/Uniforms/Pants_M88/Pants_M88_CDF.et"
    }
   }
   CRF_Clothing "{629F78CE67CB3C4C}" {
    m_ClothingPrefabs {
     "{7C828AB80ED1D9B0}Prefabs/Characters/Footwear/Boots_Faradey_906/Footware_Faradey_906.et"
    }
   }
   CRF_Clothing "{629F78CE67CB3C48}" {
    m_ClothingPrefabs {
     "{121112B27DF888B2}Prefabs/Characters/Vests/Vest_TV110/Variants/Vest_TV110_arsarmaHSGI_OD.et"
     "{2C5A109A7F2C13DD}Prefabs/Characters/Vests/Vest_TV110/Variants/Vest_TV110_arsarmaHSGI_OD_3.et"
    }
   }
   CRF_Clothing "{629F78CE67CB3C40}" {
    m_ClothingPrefabs {
     ""
     "{4F71E7468E78DDD2}Prefabs/Characters/Handwear/Gloves_Leather_01/Gloves_Leather_01.et"
     "{A29726AEB46AD13E}Prefabs/Characters/Handwear/Gloves_Wool_01/Gloves_Wool_Khaki_01.et"
    }
   }
  }
 }
}