PersistenceSystemConfig : "{8532E1DD4E714D95}Configs/Systems/Persistence/Mission.conf" {
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Player {
     Configurations {
      EntityPersistenceConfig "{6A0E1933BE5BD141}" {
       Rule EntityClassPersistenceConfigRule "{6572819621E8D479}" {
        EntityClass "COA_PlayerController"
       }
       Collection "{6572819669ACAF54}"
      }
     }
    }
   }
  }
 }
 PersistentStates {
  COA_GamemodeStateData "{6A0D5B73E87BBCBD}" {
  }
  COA_RespawnManagerStateData "{6A0D5B73ED4F7233}" {
  }
  COA_SlottingManagerStateData "{6A0D5B73E32F5A15}" {
  }
  SCR_GameMasterMetaData "{6A0D5B73E2FABDD9}" {
  }
 }
}