CRF_GearScriptConfig {
 m_FactionName "hostage mf"
 m_FactionIcon "{B6755353B5308DD3}UI/Textures/EditorPreviews/Characters/CIV/Character_CIV_Businessman_2.edds"
 m_FactionIdentity "{C6DC7F818DAA149A}Configs/Identities/custom/fluff/CRF_CharacterIdentity_HVT_SubArma.conf"
 m_DefaultClothing {
  CRF_Clothing "{68650ACBAF8E9809}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{52AB6EC3FE535303}Prefabs/Characters/Uniforms/Jacket_Suit_01/Jacket_Suit_01_Brown_V1.et"
   }
  }
  CRF_Clothing "{68650ACBAC4E04C3}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{E65D5C9848AC18E9}Prefabs/Characters/Uniforms/Pants_Suit_01/Pants_Suit_01_brown_V1.et"
   }
  }
  CRF_Clothing "{68650ACBAC14BFAD}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{FFB63AAA810DB67A}Prefabs/Characters/Footwear/TakShoes05.et"
   }
  }
 }
 m_bEnableLeadershipBinoculars 0
 m_bEnableAssistantBinoculars 0
 m_RolesToSetCustomSettings {
  CRF_Role_Custom_Gear "{68650ACBC9901731}" {
   m_Role VIP
   m_sRoleName "Factory Owner"
  }
 }
}