SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{57F5C01A596CAE27}Prefabs/Compositions/SupplyArsenal/SupplyArsenal_INDFOR.et"
  "{BF696D299A4104B6}Prefabs/Compositions/SupplyArsenal_NoSupply/SupplyArsenalNoSupply_INDFOR.et"
 }
}