SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{DFA78D45BD5C4C5D}Prefabs/Compositions/SupplyArsenal/SupplyArsenal_BLUFOR.et"
  "{2213786125174561}Prefabs/Compositions/SupplyArsenal_NoSupply/SupplyArsenalNoSupply_BLUFOR.et"
 }
}