SCR_PlaceableEntitiesRegistry {
 m_Prefabs {
  "{3C51AF203A05A29D}Prefabs/Groups/INDFOR/Infantry/CRF_INDFOR_RifleSquad_p.et"
  "{D6EC61ED76A7D3BD}Prefabs/Groups/INDFOR/Infantry/CRF_INDFOR_FiresTeam_p.et"
  "{72D976B2B2E5F2CB}Prefabs/Groups/INDFOR/Infantry/CRF_INDFOR_ManenuverTeam_p.et"
  "{A25CB98DFE21E24D}Prefabs/Groups/INDFOR/Infantry/CRF_INDFOR_MixedTeam_p.et"
  "{9CEBE6AD697630E4}Prefabs/Groups/INDFOR/Support/CRF_INDFOR_AATeam_p.et"
  "{F251D7F709224339}Prefabs/Groups/INDFOR/Support/CRF_INDFOR_HATTeam_p.et"
  "{E671E4F1D958F3D6}Prefabs/Groups/INDFOR/Support/CRF_INDFOR_HMGTeam_p.et"
  "{B0CFD1E121D5C560}Prefabs/Groups/INDFOR/Support/CRF_INDFOR_MATTeam_p.et"
  "{A4EFE2E7F1AF758F}Prefabs/Groups/INDFOR/Support/CRF_INDFOR_MMGTeam_p.et"
  "{2B1D6C750FFC353D}Prefabs/Groups/INDFOR/Vehicle/CRF_INDFOR_VehicleCrew_p.et"
  "{69669F9DF8487C42}Prefabs/Groups/INDFOR/Vehicle/CRF_INDFOR_AirCrew_p.et"
  "{57F5C01A596CAE27}Prefabs/Compositions/SupplyArsenal/SupplyArsenal_INDFOR.et"
  "{BF696D299A4104B6}Prefabs/Compositions/SupplyArsenal_NoSupply/SupplyArsenalNoSupply_INDFOR.et"
  "{A8C13E34C9597EA4}PrefabsMissionMaking/Systems/SpawnPoints/INDFOR_Spawn.et"
  "{D119AD05F564234A}Prefabs/Vehicles/MSPs/INDFOR_MSP.et"
  "{DF75A01974E8FD17}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_AMMO.et"
  "{9712B926F1FD286E}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_ARSENAL.et"
  "{BE5E3156E28F3009}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_COMMAND.et"
  "{104037BA2BE7C414}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_ENGI.et"
  "{89D6A3C482766AE9}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_REPAIR.et"
  "{4B5522FC55DC3B0F}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_TANKER.et"
 }
}