SCR_PlaceableEntitiesRegistry {
 m_Prefabs {
  "{8AA6789CBC9922E8}Prefabs/Groups/OPFOR/Infantry/CRF_OPFOR_RifleSquad_p.et"
  "{8521BF621CA1FCC2}Prefabs/Groups/OPFOR/Infantry/CRF_OPFOR_FiresTeam_p.et"
  "{96C019744EBE6215}Prefabs/Groups/OPFOR/Infantry/CRF_OPFOR_ManenuverTeam_p.et"
  "{F19167029427CD32}Prefabs/Groups/OPFOR/Infantry/CRF_OPFOR_MixedTeam_p.et"
  "{E6B8DCBD2B2049A1}Prefabs/Groups/OPFOR/Support/CRF_OPFOR_AATeam_p.et"
  "{C6AE43FD4B441DBF}Prefabs/Groups/OPFOR/Support/CRF_OPFOR_HATTeam_p.et"
  "{D28E70FB9B3EAD50}Prefabs/Groups/OPFOR/Support/CRF_OPFOR_HMGTeam_p.et"
  "{843045EB63B39BE6}Prefabs/Groups/OPFOR/Support/CRF_OPFOR_MATTeam_p.et"
  "{901076EDB3C92B09}Prefabs/Groups/OPFOR/Support/CRF_OPFOR_MMGTeam_p.et"
  "{8EC6B2FB5C407949}Prefabs/Groups/OPFOR/Vehicle/CRF_OPFOR_VehicleCrew_p.et"
  "{22D3FEA2B2DF636D}Prefabs/Groups/OPFOR/Vehicle/CRF_OPFOR_AirCrew_p.et"
  "{819EA607D9A546AD}Prefabs/Compositions/SupplyArsenal/SupplyArsenal_OPFOR.et"
  "{C93E5964759082FF}Prefabs/Compositions/SupplyArsenal_NoSupply/SupplyArsenalNoSupply_OPFOR.et"
  "{0B3312C6940005B9}PrefabsMissionMaking/Systems/SpawnPoints/OPFOR_Spawn.et"
  "{0AAB05F13990369D}Prefabs/Vehicles/MSPs/OPFOR_MSP.et"
  "{8759EDBCF78920B7}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_AMMO.et"
  "{3927510D48AB7EB5}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_ARSENAL.et"
  "{106BD97D5BD966D2}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_COMMAND.et"
  "{486C7A1FA88619B4}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_ENGI.et"
  "{1F248314047F79CF}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_REPAIR.et"
  "{DDA7022CD3D52829}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_TANKER.et"
 }
}