SCR_PlaceableEntitiesRegistry {
 m_sSourceDirectory "{C502C0D612FB13CE}Prefabs"
 m_Prefabs {
  "{92F50F60726EB86D}Prefabs/AI Groups/OPFOR/Infantry/CRF_OPFOR_RifleSquad_p.et"
  "{6530970B482EC2C9}Prefabs/AI Groups/OPFOR/Infantry/CRF_OPFOR_FiresTeam_p.et"
  "{40BDCFD05BC6FB71}Prefabs/AI Groups/OPFOR/Infantry/CRF_OPFOR_ManeuverTeam_p.et"
  "{0EB8B97402359F01}Prefabs/AI Groups/OPFOR/Infantry/CRF_OPFOR_MixedTeam_p.et"
  "{2A01769C204DED43}Prefabs/AI Groups/OPFOR/Support/CRF_OPFOR_AATeam_p.et"
  "{B59DD6C21C181C43}Prefabs/AI Groups/OPFOR/Support/CRF_OPFOR_HATTeam_p.et"
  "{F703D0D434EF9A1A}Prefabs/AI Groups/OPFOR/Support/CRF_OPFOR_HMGTeam_p.et"
  "{A1BDE5C4CC62ACAC}Prefabs/AI Groups/OPFOR/Support/CRF_OPFOR_MATTeam_p.et"
  "{E323E3D2E4952AF5}Prefabs/AI Groups/OPFOR/Support/CRF_OPFOR_MMGTeam_p.et"
  "{E5143827D374F6DD}Prefabs/AI Groups/OPFOR/Vehicle/CRF_OPFOR_VehicleCrew_p.et"
  "{67CF9BB46BE94DF0}Prefabs/AI Groups/OPFOR/Vehicle/CRF_OPFOR_AirCrew_p.et"
  "{819EA607D9A546AD}Prefabs/Compositions/SupplyArsenal/SupplyArsenal_OPFOR.et"
  "{C93E5964759082FF}Prefabs/Compositions/SupplyArsenal_NoSupply/SupplyArsenalNoSupply_OPFOR.et"
  "{0B3312C6940005B9}PrefabsMissionMaking/Systems/SpawnPoints/OPFOR_Spawn.et"
  "{0AAB05F13990369D}Prefabs/Vehicles/MSPs/OPFOR_MSP.et"
  "{8759EDBCF78920B7}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_AMMO.et"
  "{3927510D48AB7EB5}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_ARSENAL.et"
  "{106BD97D5BD966D2}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_COMMAND.et"
  "{486C7A1FA88619B4}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_ENGI.et"
  "{1F248314047F79CF}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_REPAIR.et"
  "{DDA7022CD3D52829}Prefabs/Vehicles/Wheeled/Ural4320/OPFOR/OPFOR_TANKER.et"
 }
}