SCR_PlaceableEntitiesRegistry {
 m_sSourceDirectory "{777229AAD1E0299B}Prefabs/Characters/Factions"
 m_Prefabs {
  "{ADF09DD7FCCA37C3}Prefabs/AI Groups/INDFOR/Infantry/CRF_INDFOR_RifleSquad_p.et"
  "{A652C7FD71AA78C0}Prefabs/AI Groups/INDFOR/Infantry/CRF_INDFOR_FiresTeam_p.et"
  "{5CC96E909C94EAE0}Prefabs/AI Groups/INDFOR/Infantry/CRF_INDFOR_ManeuverTeam_p.et"
  "{D2E21F9DF92C4930}Prefabs/AI Groups/INDFOR/Infantry/CRF_INDFOR_MixedTeam_p.et"
  "{F894CE09B5815A68}Prefabs/AI Groups/INDFOR/Support/CRF_INDFOR_AATeam_p.et"
  "{5CE8053CC099A39D}Prefabs/AI Groups/INDFOR/Support/CRF_INDFOR_HATTeam_p.et"
  "{48C8363A10E31372}Prefabs/AI Groups/INDFOR/Support/CRF_INDFOR_HMGTeam_p.et"
  "{1E76032AE86E25C4}Prefabs/AI Groups/INDFOR/Support/CRF_INDFOR_MATTeam_p.et"
  "{0A56302C3814952B}Prefabs/AI Groups/INDFOR/Support/CRF_INDFOR_MMGTeam_p.et"
  "{CE21A9AD1526A581}Prefabs/AI Groups/INDFOR/Vehicle/CRF_INDFOR_VehicleCrew_p.et"
  "{A95EA25C8833C6BE}Prefabs/AI Groups/INDFOR/Vehicle/CRF_INDFOR_AirCrew_p.et"
  "{57F5C01A596CAE27}Prefabs/Compositions/SupplyArsenal/SupplyArsenal_INDFOR.et"
  "{BF696D299A4104B6}Prefabs/Compositions/SupplyArsenal_NoSupply/SupplyArsenalNoSupply_INDFOR.et"
  "{A8C13E34C9597EA4}PrefabsMissionMaking/Systems/SpawnPoints/INDFOR_Spawn.et"
  "{D119AD05F564234A}Prefabs/Vehicles/MSPs/INDFOR_MSP.et"
  "{DF75A01974E8FD17}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_AMMO.et"
  "{9712B926F1FD286E}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_ARSENAL.et"
  "{BE5E3156E28F3009}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_COMMAND.et"
  "{104037BA2BE7C414}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_ENGI.et"
  "{89D6A3C482766AE9}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_REPAIR.et"
  "{4B5522FC55DC3B0F}Prefabs/Vehicles/Wheeled/Ural4320/INDFOR/INDFOR_TANKER.et"
 }
}