SCR_PlaceableEntitiesRegistry {
 m_Prefabs {
  "{A21AABD4235A65F5}Prefabs/Groups/CIV/Infantry/CRF_CIV_RifleSquad_p.et"
  "{A283F8F0F9A12425}Prefabs/Compositions/SupplyArsenal/SupplyArsenal_CIV.et"
  "{3324FCADDE3D4D31}Prefabs/Compositions/SupplyArsenal_NoSupply/SupplyArsenalNoSupply_CIV.et"
  "{91AC884B31EDEE23}PrefabsMissionMaking/Systems/SpawnPoints/CIV_Spawn.et"
  "{E05C482DC753626A}Prefabs/Vehicles/MSPs/CIV_MSP.et"
 }
}