SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{819EA607D9A546AD}Prefabs/Compositions/SupplyArsenal/SupplyArsenal_OPFOR.et"
  "{C93E5964759082FF}Prefabs/Compositions/SupplyArsenal_NoSupply/SupplyArsenalNoSupply_OPFOR.et"
 }
}