SCR_PlaceableEntitiesRegistry {
 m_Prefabs {
  "{9C45BAF40F909576}Prefabs/Groups/BLUFOR/Infantry/CRF_BLUFOR_RifleSquad_p.et"
  "{228B37FE23B114B7}Prefabs/Groups/BLUFOR/Infantry/CRF_BLUFOR_FiresTeam_p.et"
  "{F66A634CC3344A8C}Prefabs/Groups/BLUFOR/Infantry/CRF_BLUFOR_ManenuverTeam_p.et"
  "{E13F0A7383F37744}Prefabs/Groups/BLUFOR/Infantry/CRF_BLUFOR_MixedTeam_p.et"
  "{59473283AB54B727}Prefabs/Groups/BLUFOR/Support/CRF_BLUFOR_AATeam_p.et"
  "{79B9994E1B530F97}Prefabs/Groups/BLUFOR/Support/CRF_BLUFOR_HATTeam_p.et"
  "{6D99AA48CB29BF78}Prefabs/Groups/BLUFOR/Support/CRF_BLUFOR_HMGTeam_p.et"
  "{3B279F5833A489CE}Prefabs/Groups/BLUFOR/Support/CRF_BLUFOR_MATTeam_p.et"
  "{2F07AC5EE3DE3921}Prefabs/Groups/BLUFOR/Support/CRF_BLUFOR_MMGTeam_p.et"
  "{5804AD2759E17E13}Prefabs/Groups/BLUFOR/Vehicle/CRF_BLUFOR_VehicleCrew_p.et"
  "{ABEBD4386CA25E24}Prefabs/Groups/BLUFOR/Vehicle/CRF_BLUFOR_AirCrew_p.et"
  "{62865C82AB534D91}PrefabsMissionMaking/Systems/SpawnPoints/BLUFOR_Spawn.et"
  "{DFA78D45BD5C4C5D}Prefabs/Compositions/SupplyArsenal/SupplyArsenal_BLUFOR.et"
  "{2213786125174561}Prefabs/Compositions/SupplyArsenal_NoSupply/SupplyArsenalNoSupply_BLUFOR.et"
  "{81A2910690EDA9E5}Prefabs/Vehicles/MSPs/BLUFOR_MSP.et"
  "{C8D62059548EC894}Prefabs/Vehicles/Wheeled/M923A1/BLUFOR/BLUFOR_AMMO.et"
  "{FF65607D073A8981}Prefabs/Vehicles/Wheeled/M923A1/BLUFOR/BLUFOR_ARSENAL.et"
  "{D629E80D144891E6}Prefabs/Vehicles/Wheeled/M923A1/BLUFOR/BLUFOR_COMMAND.et"
  "{07E3B7FA0B81F197}Prefabs/Vehicles/Wheeled/M923A1/BLUFOR/BLUFOR_ENGI.et"
  "{99D8E96526104CCD}Prefabs/Vehicles/Wheeled/M923A1/BLUFOR/BLUFOR_REPAIR.et"
  "{5B5B685DF1BA1D2B}Prefabs/Vehicles/Wheeled/M923A1/BLUFOR/BLUFOR_TANKER.et"
 }
}