SCR_PlaceableEntitiesRegistry {
 m_Prefabs {
  "{876962859AB1C740}Prefabs/Systems/Explosions/Wrapper_Bomb_Grenade.et"
  "{8102F444C2905DFA}Prefabs/Systems/Explosions/Wrapper_Bomb_RPG.et"
  "{A79737B19CBFD5EC}Prefabs/Systems/Explosions/Wrapper_Bomb_Large.et"
  "{DDDDBEC77B49A995}Prefabs/Systems/Explosions/Wrapper_Bomb_Huge.et"
  "{954E95A3DC2202C2}Prefabs/Systems/Fire/Wrapper_Fire_Small_Damage.et"
  "{81EA5D4928E33D47}Prefabs/Systems/Fire/Wrapper_Fire_Medium_Damage.et"
  "{4BE47BA2B7E3877E}Prefabs/Systems/Fire/Wrapper_Fire_Large_Damage.et"
  "{A5D31A83049F484B}Prefabs/Systems/Smoke/Wrapper_Smoke_ANM8.et"
  "{6BDBEFF5CE6E2F28}Prefabs/Systems/Smoke/Wrapper_Smoke_Green.et"
  "{2D854F52D8D6B31E}Prefabs/Systems/Smoke/Wrapper_Smoke_Purple.et"
  "{49EBEAAC42260651}Prefabs/Systems/Smoke/Wrapper_Smoke_Red.et"
  "{1D8922C3FE426E4E}Prefabs/Systems/Smoke/Wrapper_Smoke_Yellow.et"
  "{C4A16F2433002F7E}Prefabs/Systems/Smoke/Wrapper_Smoke_Inf_Black_Large.et"
  "{BA566A63A8BCE092}Prefabs/Systems/Smoke/Wrapper_Smoke_Inf_White_Large.et"
  "{49D3A377C712648B}Prefabs/Systems/Flare/Wrapper_Flare_Parachute_Red.et"
  "{B9B185514D6F61A6}Prefabs/Systems/Flare/Wrapper_Flare_Parachute_White.et"
  "{7CA4A592F8520753}Prefabs/Systems/Artillery/ArtilleryWrapper_Small.et"
  "{E0CDE19D1D5E4400}Prefabs/Systems/Artillery/ArtilleryWrapper_Medium.et"
  "{217346AE0EBEDD8F}Prefabs/Systems/Artillery/ArtilleryWrapper_Large.et"
  "{16C019598C940565}Prefabs/Systems/Artillery/ArtilleryWrapper_Huge.et"
  "{30263B4F1FB2A0F2}Prefabs/Systems/Artillery/ArtilleryWrapper_WTF.et"
  "{09EC8E5951A92216}Prefabs/Systems/Artillery/ArtilleryWrapper_Cluster.et"
  "{570DBF0BE57D2038}Prefabs/Systems/Artillery/ArtilleryBarrage_Small.et"
  "{D0DA67C9F501A6D5}Prefabs/Systems/Artillery/ArtilleryBarrage_Medium.et"
  "{0ADA5C371391FAE4}Prefabs/Systems/Artillery/ArtilleryBarrage_Large.et"
  "{35E0DB90D652D713}Prefabs/Systems/Artillery/ArtilleryBarrage_Huge.et"
  "{E5095FF5E1E226D6}Prefabs/Systems/Artillery/ArtilleryBarrage_Huger.et"
  "{B42D53B1BF697927}Prefabs/Systems/Artillery/ArtilleryBarrage_Cluster.et"
  "{E1BBAB7F28FE8B0B}Prefabs/Systems/Mines/Mine_AP.et"
  "{B0DBBAA7E1568D12}Prefabs/Systems/Mines/Mine_AT.et"
  "{889F8827B203CE19}Prefabs/Systems/Fireworks/FireworkSpawner_single.et"
  "{6B5757AC80792834}Prefabs/Systems/Fireworks/FireworkSpawner_smallRandom.et"
  "{59EC39C0628DA84F}Prefabs/Systems/Fireworks/FireworkSpawner_bigRandom.et"
  "{6543141E2B6EA9AF}Prefabs/Systems/Sound/sound_backgroundcombat.et"
  "{93FC2145F05A1EEE}Prefabs/Systems/Sound/sound_airraidsiren.et"
  "{C0495641D47CADF5}Prefabs/Systems/Sound/sound_siren_incoming.et"
  "{C5341109EB1AB7B5}Prefabs/Destructible/GMFX_Destructible_Radar_RPL5.et"
  "{FFCDFB1375A99125}Prefabs/Destructible/GMFX_Destructible_RPL5_01_generator.et"
  "{EA3F58CE2AF832FD}Prefabs/Destructible/RedBarrel/GMFX_RedBarrel.et"
  "{8B9AFAD3A1548FCE}Prefabs/Destructible/AmmoStorage/GMFX_AmmoStorage.et"
  "{4C931B452C796A2A}Prefabs/Destructible/AmmoStorage/GMFX_AmmoStorage_USSR.et"
  "{1D32273356636E89}Prefabs/Systems/Gas/Wrapper_Gas_base.et"
  "{544B7E088E789058}Prefabs/Systems/Gas/Wrapper_Gas_Covid.et"
  "{3399B41124F52F47}Prefabs/Systems/Artillery/ArtilleryWrapper_TacNuke.et"
 }
}