SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60E6ED13E10B72D7}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{65D94ED077910CDC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{688758931792A7A2}" {
     m_bEnabled 0
    }
   }
  }
 }
}