CRF_GearScriptEquipmentConfig {
 m_aRolesThatGetLeadershipRadios {
  CRF_Role "{64FB05E53B0FDBBB}" {
   m_sRole "Company Commander"
  }
  CRF_Role "{64FB05E2721C7A7C}" {
   m_sRole "First Sergeant"
  }
  CRF_Role "{64FB05E273F66317}" {
   m_sRole "Platoon Leader"
  }
  CRF_Role "{64FB05E273615B7A}" {
   m_sRole "Platoon Sergeant"
  }
  CRF_Role "{64FB05E272B9AEDA}" {
   m_sRole "Medical Officer"
  }
  CRF_Role "{64FB05E270774AE6}" {
   m_sRole "Forward Observer"
  }
  CRF_Role "{64FB05E26133CD9A}" {
   m_sRole "JTAC"
  }
  CRF_Role "{64FB05E260C00AC2}" {
   m_sRole "Squad Lead"
  }
  CRF_Role "{64FB05E26059A6B1}" {
   m_sRole "Vehicle Lead"
  }
  CRF_Role "{64FB05E267C243AB}" {
   m_sRole "Indirect Lead"
  }
  CRF_Role "{64FB05E2675FDBDA}" {
   m_sRole "Logi Lead"
  }
  CRF_Role "{64FB05E266D98993}" {
   m_sRole "Medic"
  }
  CRF_Role "{64FB05E3915EBC0B}" {
   m_sRole "Pilot"
  }
  CRF_Role "{64FB05E385C30F17}" {
   m_sRole "Spotter"
  }
  CRF_Role "{64FB05E38740200A}" {
   m_sRole "Crew Chief"
  }
 }
 m_aRolesThatGetRTORadios {
  CRF_Role "{64FB05E3CFA9E299}" {
   m_sRole "Radio Telephone Operator"
  }
 }
 m_aRolesThatGetLeadershipBinos {
  CRF_Role "{64FB05E35EB5AB70}" {
   m_sRole "Company Commander"
  }
  CRF_Role "{64FB05E3594A76F8}" {
   m_sRole "First Sergeant"
  }
  CRF_Role "{64FB05E34439DAAB}" {
   m_sRole "Platoon Leader"
  }
  CRF_Role "{64FB05E35B7E1E15}" {
   m_sRole "Platoon Sergeant"
  }
  CRF_Role "{64FB05E35B01C352}" {
   m_sRole "Medical Officer"
  }
  CRF_Role "{64FB05E35AA0B943}" {
   m_sRole "Forward Observer"
  }
  CRF_Role "{64FB05E35A58AC5D}" {
   m_sRole "JTAC"
  }
  CRF_Role "{64FB05E359F0951C}" {
   m_sRole "Squad Lead"
  }
  CRF_Role "{64FB05E35996DA55}" {
   m_sRole "Vehicle Lead"
  }
  CRF_Role "{64FB05E35F8C4D7E}" {
   m_sRole "Indirect Lead"
  }
  CRF_Role "{64FB05E3580CFB3B}" {
   m_sRole "Logi Lead"
  }
  CRF_Role "{64FB05E35879D2E5}" {
   m_sRole "Team Lead"
  }
  CRF_Role "{64FB05E36C7BB006}" {
   m_sRole "Spotter"
  }
 }
 m_aRolesThatGetAssistantBinos {
  CRF_Role "{64FB05E3F13699D2}" {
   m_sRole "Assistant Automatic Rifleman"
  }
  CRF_Role "{64FB05E3F2B3FA38}" {
   m_sRole "Assistant Rifleman AntiTank"
  }
  CRF_Role "{64FB05E3FC4D3E77}" {
   m_sRole "Assistant Heavy AntiTank"
  }
  CRF_Role "{64FB05E3F3E0915B}" {
   m_sRole "Assistant Medium AntiTank"
  }
  CRF_Role "{64FB05E3F380457D}" {
   m_sRole "Assistant Heavy MachineGun"
  }
  CRF_Role "{64FB05E3F3244F23}" {
   m_sRole "Assistant Medium MachineGun"
  }
  CRF_Role "{64FB05E3F2407ECA}" {
   m_sRole "Assistant Anit-Air"
  }
 }
 m_aRolesThatGetAssistantMags {
  CRF_Role "{64FC595570584D2E}" {
   m_sRole "Assistant Automatic Rifleman"
  }
  CRF_Role "{64FC595578DA7FF8}" {
   m_sRole "Assistant Rifleman AntiTank"
  }
  CRF_Role "{64FC59557CF40BD3}" {
   m_sRole "Assistant Heavy AntiTank"
  }
  CRF_Role "{64FC5955783319B9}" {
   m_sRole "Assistant Medium AntiTank"
  }
  CRF_Role "{64FC59557F9AB28B}" {
   m_sRole "Assistant Heavy MachineGun"
  }
  CRF_Role "{64FC59557ED66DD1}" {
   m_sRole "Assistant Medium MachineGun"
  }
  CRF_Role "{64FC59556DF3610A}" {
   m_sRole "Assistant Anit-Air"
  }
 }
 m_aRolesThatGetMedicalItems {
  CRF_Role "{64FB05E3FE1AA345}" {
   m_sRole "Medical Officer"
  }
  CRF_Role "{64FB05E3FEB6D39F}" {
   m_sRole "Medic"
  }
 }
}