CRF_GearScriptEquipmentConfig {
 m_aRolesThatGetLeadershipRadios {
  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  13
  39
  33
  40
 }
 m_aRolesThatGetRTORadios {
  14
 }
 m_aRolesThatGetLeadershipBinos {
  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12
  33
 }
 m_aRolesThatGetAssistantBinos {
  17
  20
  23
  25
  27
  29
  29
 }
 m_aRolesThatGetAssistantMags {
  17
  20
  23
  25
  27
  29
  29
 }
 m_aRolesThatGetMedicalItems {
  5
  13
 }
}