CRF_SightArsenalConfig {
 m_aSights {
  "{FE2896D202FE7449}Prefabs/Weapons/Attachments/Optics/1p63/Optic_1P63.et"
  "{C4B57488909B3B63}Prefabs/Weapons/Attachments/Optics/1p87/Optic_1P87.et"
  "{349DE19C84303C7B}Prefabs/Weapons/Attachments/Optics/1p87/Optic_1P87_new.et"
  "{979AF6CFF2AAAE26}Prefabs/Weapons/Attachments/Optics/aimpoint_t1/Optic_su278pvs_high.et"
  "{B0D87E5898D91004}Prefabs/Weapons/Attachments/Optics/aimpoint_t1/Optic_su278pvs_low.et"
  "{482B9B157016B0DC}Prefabs/Weapons/Attachments/Optics/aimpoint_t1/Optic_t1_base.et"
  "{1DAEA9434BBB003E}Prefabs/Weapons/Attachments/Optics/aimpoint_t1/Optic_t1_low.et"
  "{4268B2077766E8C7}Prefabs/Weapons/Attachments/Optics/aimpoint_t1/Optic_t1_high.et"
  "{9C42803E49305273}Prefabs/Weapons/Attachments/Optics/exps/Optic_EXPS3-1.et"
  "{0A697FF8CA33F9A5}Prefabs/Weapons/Attachments/Optics/exps/Optic_EXPS3-1_tan.et"
  "{F016B4DEF5F4DD5D}Prefabs/Weapons/Attachments/Optics/exps/Optic_EXPS3-2.et"
  "{B8BE3D139591CA3D}Prefabs/Weapons/Attachments/Optics/exps/Optic_EXPS3-2_tan.et"
  "{158AF827F9114A36}Prefabs/Weapons/Attachments/Optics/exps/Optic_EXPS3-3.et"
  "{D6F3034AA0F024B5}Prefabs/Weapons/Attachments/Optics/exps/Optic_EXPS3-3_tan.et"
  "{7A384E61D86D580F}Prefabs/Weapons/Attachments/Optics/exps/Optic_su231A_base.et"
  "{D0453107F44917CF}Prefabs/Weapons/Attachments/Optics/exps/Optic_su231A_black.et"
  "{67F7BD007D153A98}Prefabs/Weapons/Attachments/Optics/exps/Optic_su231A_camo.et"
  "{4AF36B835267F3ED}Prefabs/Weapons/Attachments/Optics/exps/Optic_su231A_tan.et"
  "{ACDF49FACD0701A8}Prefabs/Weapons/Attachments/Optics/Scopes/Optic_1P29/Optic_1P29.et"
 }
}