CRF_GearScriptWeaponsConfig {
 m_aRolesThatGetRifles {
  CRF_Role "{64FB05E1B90473F6}" {
  }
  CRF_Role "{64FB05E1A23E9EE1}" {
  }
  CRF_Role "{64FB05E1A2956121}" {
  }
  CRF_Role "{64FB05E1A014CABC}" {
  }
  CRF_Role "{64FB05E1A1D19BD4}" {
  }
  CRF_Role "{64FB05CA072D2AF5}" {
  }
  CRF_Role "{64FB05E1A08CBD14}" {
  }
  CRF_Role "{64FB05CA01C9CB35}" {
  }
  CRF_Role "{64FB05E1A7CC8BC5}" {
  }
  CRF_Role "{64FB05E1A6E65733}" {
  }
  CRF_Role "{64FB05E1A683BFEF}" {
  }
  CRF_Role "{64FB05CA0142AAB9}" {
  }
  CRF_Role "{64FB05E1A63FBF98}" {
  }
  CRF_Role "{64FB05E1A46353AE}" {
  }
 }
 m_aRolesThatGetRifleUGLs {
  CRF_Role "{64FB05E6DEFE667D}" {
  }
  CRF_Role "{64FB05E6D9266A3A}" {
  }
  CRF_Role "{64FB05E6DBD6894D}" {
  }
  CRF_Role "{64FB05E6DAD6E62C}" {
  }
  CRF_Role "{64FB05E6DB77DF01}" {
  }
  CRF_Role "{64FB05E6DA5F57BC}" {
  }
  CRF_Role "{64FB05E6D9F57CD3}" {
  }
  CRF_Role "{64FB05E6D99BAE8A}" {
  }
  CRF_Role "{64FB05E6D8312475}" {
  }
  CRF_Role "{64FB05E6F89DAF6B}" {
  }
  CRF_Role "{64FB05E6F80AF2D8}" {
  }
  CRF_Role "{64FB05E6ECF10043}" {
  }
  CRF_Role "{64FB05E6EA9D05F2}" {
  }
  CRF_Role "{64FB05E1ABFDEED6}" {
  }
 }
 m_aRolesThatGetCarbines {
  CRF_Role "{64FB059903993D41}" {
  }
  CRF_Role "{64FB0599EF4874E4}" {
  }
  CRF_Role "{64FB0599E8FFE262}" {
  }
  CRF_Role "{64FB0599E898D2EE}" {
  }
  CRF_Role "{64FB059900884EED}" {
  }
  CRF_Role "{64FB05990102355E}" {
  }
  CRF_Role "{64FB05990228B7C7}" {
  }
  CRF_Role "{64FB059902B1C450}" {
  }
  CRF_Role "{650311B4C5E9A50C}" {
  }
 }
 m_aRolesThatGetPistols {
  CRF_Role "{64FB05995B69E597}" {
  }
  CRF_Role "{64FB0599465EC9A8}" {
  }
  CRF_Role "{64FB05994049271D}" {
  }
  CRF_Role "{64FB059941141EC0}" {
  }
  CRF_Role "{64FB059940A28D32}" {
  }
  CRF_Role "{64FB059947DAF037}" {
  }
  CRF_Role "{64FB059945E08743}" {
  }
  CRF_Role "{64FB0599451C00D3}" {
  }
  CRF_Role "{64FB05996F4F3F56}" {
  }
  CRF_Role "{64FB05E693376C55}" {
  }
  CRF_Role "{64FB05E69D4169A6}" {
  }
  CRF_Role "{64FB05E69CE8C922}" {
  }
  CRF_Role "{64FB05E69C7B20D8}" {
  }
  CRF_Role "{64FB05E69C0B465C}" {
  }
  CRF_Role "{64FB05E68E2A0BCE}" {
  }
  CRF_Role "{64FB05E6896DDDC1}" {
  }
  CRF_Role "{64FB05E688BBDC35}" {
  }
  CRF_Role "{650311B55FD0B231}" {
  }
 }
 m_aRolesThatGetARs {
  CRF_Role "{64FB0599BA756738}" {
   m_iRole AUTOMATIC_RIFLEMAN
  }
 }
 m_aRolesThatGetMMGs {
  CRF_Role "{64FB0599B969D2EF}" {
  }
 }
 m_aRolesThatGetHMGs {
  CRF_Role "{64FB0599B82A0E6A}" {
  }
 }
 m_aRolesThatGetAT {
  CRF_Role "{64FB0599BF4CB077}" {
  }
 }
 m_aRolesThatGetMAT {
  CRF_Role "{64FB0599BE979A84}" {
  }
 }
 m_aRolesThatGetHAT {
  CRF_Role "{64FB05996B3D9542}" {
  }
 }
 m_aRolesThatGetAA {
  CRF_Role "{64FB0599BDC40057}" {
  }
 }
 m_aRolesThatGetSnipers {
  CRF_Role "{64FB0599BC887020}" {
  }
 }
}