CRF_GearScriptRolesConfig {
 m_RoleConfigs {
  CRF_RoleConfig "{65A101E4F2EAE258}" {
   m_BluforVariant "{42C91BDBD19B390A}Prefabs/Characters/Factions/BLUFOR/CRF_GS_BLUFOR_Unarmed_P.et"
   m_OpforVariant "{CCCC8B00AE564C31}Prefabs/Characters/Factions/OPFOR/CRF_GS_OPFOR_Unarmed_P.et"
   m_IndforVariant "{9DB9EB994D1BBCDB}Prefabs/Characters/Factions/INDFOR/CRF_GS_INDFOR_Unarmed_P.et"
   m_CivVariant "{1C7A4720A7B2239C}Prefabs/Characters/Factions/CIV/CRF_GS_CIV_Unarmed_P.et"
   m_aWeapons {
   }
  }
  CRF_RoleConfig "{65A101EB42085DA9}" {
   m_Role COMPANY_COMMANDER
   m_BluforVariant "{B3182F73DBEACB7B}Prefabs/Characters/Factions/BLUFOR/CRF_GS_BLUFOR_COY_P.et"
   m_OpforVariant "{37DE97333EEFF4BB}Prefabs/Characters/Factions/OPFOR/CRF_GS_OPFOR_COY_P.et"
   m_IndforVariant "{A53B8AB60784E018}Prefabs/Characters/Factions/INDFOR/CRF_GS_INDFOR_COY_P.et"
   m_CivVariant "{66A37C085C2B2873}Prefabs/Characters/Factions/CIV/CRF_GS_CIV_COY_P.et"
   m_aWeapons {
    1
    4
   }
   m_aMagazines {
    1
    4
   }
   m_aItems {
    1
    3
   }
  }
  CRF_RoleConfig "{65A101E4CDCCD408}" {
   m_Role FIRST_SERGEANT
   m_BluforVariant "{F5FDAAADCCD3C2F9}Prefabs/Characters/Factions/BLUFOR/CRF_GS_BLUFOR_1SG_P.et"
   m_OpforVariant "{713B12ED29D6FD39}Prefabs/Characters/Factions/OPFOR/CRF_GS_OPFOR_1SG_P.et"
   m_IndforVariant "{E3DE0F6810BDE99A}Prefabs/Characters/Factions/INDFOR/CRF_GS_INDFOR_1SG_P.et"
   m_CivVariant "{2046F9D64B1221F1}Prefabs/Characters/Factions/CIV/CRF_GS_CIV_1SG_P.et"
   m_aWeapons {
    1
    4
   }
  }
  CRF_RoleConfig "{65A101E4F2F7E230}" {
  }
  CRF_RoleConfig "{65A101E4F311E68C}" {
  }
  CRF_RoleConfig "{65A101E4F325914B}" {
  }
  CRF_RoleConfig "{65A101E4F3400A0D}" {
  }
  CRF_RoleConfig "{65A101E4F3573803}" {
  }
  CRF_RoleConfig "{65A101E4F3718C7C}" {
  }
  CRF_RoleConfig "{65A101E4F39B51D6}" {
  }
  CRF_RoleConfig "{65A101E4F3A52B80}" {
  }
  CRF_RoleConfig "{65A101E4F3C005B8}" {
  }
  CRF_RoleConfig "{65A101E4F3EA3E9B}" {
  }
  CRF_RoleConfig "{65A101E4F3F1FFEE}" {
  }
  CRF_RoleConfig "{65A101E4FC1D5C3A}" {
  }
  CRF_RoleConfig "{65A101E4FC387159}" {
  }
  CRF_RoleConfig "{65A101E4FC42B334}" {
  }
  CRF_RoleConfig "{65A101E4FC6CE082}" {
  }
  CRF_RoleConfig "{65A101E4FC770CDA}" {
  }
  CRF_RoleConfig "{65A101E4FC9208BE}" {
  }
  CRF_RoleConfig "{65A101E4FCBECBF3}" {
  }
  CRF_RoleConfig "{65A101E4FCDA1E9D}" {
  }
  CRF_RoleConfig "{65A101E4FCE5205A}" {
  }
  CRF_RoleConfig "{65A101E4FD031E3B}" {
  }
  CRF_RoleConfig "{65A101E4FD203AA7}" {
  }
  CRF_RoleConfig "{65A101E4FD4DA48C}" {
  }
  CRF_RoleConfig "{65A101E4FD6B1909}" {
  }
  CRF_RoleConfig "{65A101E4FD89323A}" {
  }
  CRF_RoleConfig "{65A101E4FD938BC2}" {
  }
  CRF_RoleConfig "{65A101E4FDC9C79F}" {
  }
 }
}