SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD58703CABF4}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{64F44635EF927951}" {
     m_sEntityPrefab "{40C84C5C9B134008}Prefabs/Weapons/Explosives/Explosive_Satchels/Throwable/INDFOR_Throwable_Satchel.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{64F4463586A53A16}" {
       m_eItemType LETHAL_THROWABLE
       m_iSupplyCost 15
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{64F4463586A53A1F}" {
         m_vItemOffset -0.015 0.015 0
         m_vItemRotation 0 -36 15.8
        }
       }
      }
      SCR_EntityCatalogSupportStationResupplyData "{64F4463586A53A1A}" {
       m_eResupplyType GRENADE
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{64F4463519936F25}" {
     m_sEntityPrefab "{00515E7AAAFD9CB6}Prefabs/Weapons/Explosives/Explosive_Satchels/INDFOR_Satchel.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{64F44635A4122CD7}" {
       m_eItemType EXPLOSIVES
      }
     }
    }
   }
  }
 }
}