CRF_GearScriptConfig {
 m_FactionName "Racists"
 m_FactionIcon "{740377C70AF5277A}CRF Images/Pie_sorryIKilledTheServer.edds"
 m_FactionIdentity "{93C4AAA0496F0B42}Configs/Identities/CRF_CharacterIdentity_American.conf"
 m_DefaultClothing {
  CRF_Clothing "{62C61C1A931770B8}" {
   m_iClothingType HEADGEAR
   m_ClothingPrefabs {
    "{F545C1BE7C99954A}Prefabs/Characters/HeadGear/Hat_Patrol_US_01/Hat_Patrol_US_01.et"
    "{9911F55EC05D1A64}Prefabs/Characters/HeadGear/Hat_Patrol_US_01/Hat_Patrol_US_02.et"
   }
  }
  CRF_Clothing "{62C61C1A931770B4}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{C7861F11D5334C0E}Prefabs/Characters/Uniforms/Jacket_US_BDU.et"
    "{293F577C298061E3}Prefabs/Characters/Uniforms/Jacket_US_BDU_02.et"
    "{3CCA7A9BB4FD3197}Prefabs/Characters/Uniforms/Jacket_US_BDU_rolledup.et"
    "{A080C1AEBF921DC4}Prefabs/Characters/Uniforms/Jacket_US_BDU_rolledup_02.et"
   }
  }
  CRF_Clothing "{62C61C1A931770B0}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{604BB72BE8E023C2}Prefabs/Characters/Uniforms/Pants_US_BDU.et"
    "{86BB79B9A2233780}Prefabs/Characters/Uniforms/Pants_US_M65.et"
   }
  }
  CRF_Clothing "{62C61C1A931770AD}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{DAAFD15478BDE1C3}Prefabs/Characters/Footwear/CombatBoots_US_01.et"
   }
  }
 }
 m_bEnableLeadershipBinoculars 0
 m_bEnableAssistantBinoculars 0
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{62C61C1A931770AA}" {
   m_sItemPrefab "{3A421547BC29F679}Prefabs/Items/Equipment/Flashlights/Flashlight_MX991/Flashlight_MX991.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C1A931770A1}" {
   m_sItemPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C1A9317709E}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
 }
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{673A73223B4ADAB9}" {
   m_sItemPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{673A73223B915544}" {
   m_sItemPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
   m_iItemCount 1
  }
 }
 m_MedicMedicalItems {
  CRF_Inventory_Item "{62C61C1A93177061}" {
   m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
   m_iItemCount 10
  }
  CRF_Inventory_Item "{62C61C1A9317705D}" {
   m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   m_iItemCount 3
  }
  CRF_Inventory_Item "{62C61C1A93177059}" {
   m_sItemPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{62C61C1A93177055}" {
   m_sItemPrefab "{5B2FD067D70C1E8F}Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{62C61C1A93177051}" {
   m_sItemPrefab "{527D7C5D2E476BDC}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_01.et"
   m_iItemCount 5
  }
  CRF_Inventory_Item "{62C61C1A9317704C}" {
   m_sItemPrefab "{21EF98BFC1EB3793}Prefabs/Items/Equipment/Kits/MedicalKit_01/MedicalKit_01_USSR.et"
   m_iItemCount 1
  }
 }
}