CRF_GearScriptConfig {
 m_FactionName "Racists"
 m_FactionIcon "{740377C70AF5277A}UI/Images/Memes/Pie_sorryIKilledTheServer.edds"
 m_FactionIdentity "{B96582A978CDF7AD}Configs/Identities/Europe/CRF_CharacterIdentity_Russian.conf"
 m_DefaultClothing {
  CRF_Clothing "{62C61C18F46C6207}" {
   m_iClothingType HEADGEAR
   m_ClothingPrefabs {
    "{2B29B7E1C6BD1048}Prefabs/Characters/HeadGear/Hat_M88_01/Hat_M88_01_v1.et"
    "{B54B78383E64268F}Prefabs/Characters/HeadGear/Hat_M88_01/Hat_M88_01_v2.et"
   }
  }
  CRF_Clothing "{62C61C18F46C6204}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{9F546CCA2582D16F}Prefabs/Characters/Uniforms/Jacket_M88.et"
    "{D262D2102B9931C6}Prefabs/Characters/Uniforms/Jacket_M88_rolledup.et"
   }
  }
  CRF_Clothing "{62C61C18F46C6202}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{DCF980831E880F6A}Prefabs/Characters/Uniforms/Pants_M88.et"
   }
  }
  CRF_Clothing "{62C61C18F46C627E}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
   }
  }
 }
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{62C61C18F46C627C}" {
   m_sItemPrefab "{575EA58E67448C2A}Prefabs/Items/Equipment/Flashlights/Flashlight_Soviet_01/Flashlight_Soviet_01.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C18F46C6273}" {
   m_sItemPrefab "{7CEF68E2BC68CE71}Prefabs/Items/Equipment/Compass/Compass_Adrianov.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{62C61C18F46C6271}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
 }
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{673A73222327C57B}" {
   m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{673A73222359E739}" {
   m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   m_iItemCount 1
  }
 }
 m_MedicMedicalItems {
  CRF_Inventory_Item "{62C61C18F46C621A}" {
   m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
   m_iItemCount 10
  }
  CRF_Inventory_Item "{62C61C18F46C6214}" {
   m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
   m_iItemCount 3
  }
  CRF_Inventory_Item "{62C61C18F46C6211}" {
   m_sItemPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{62C61C18F46C620E}" {
   m_sItemPrefab "{5B2FD067D70C1E8F}Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et"
   m_iItemCount 6
  }
  CRF_Inventory_Item "{62C61C18F46C620B}" {
   m_sItemPrefab "{527D7C5D2E476BDC}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_01.et"
   m_iItemCount 5
  }
  CRF_Inventory_Item "{62C61C18F46C620A}" {
   m_sItemPrefab "{21EF98BFC1EB3793}Prefabs/Items/Equipment/Kits/MedicalKit_01/MedicalKit_01_USSR.et"
   m_iItemCount 1
  }
 }
}