MenuManager {
 MenuPresets {
  MenuPreset PauseMenu {
   Class "CRF_PauseMenuUI"
  }
  MenuPreset Inventory20Menu {
  }
  MenuPreset EditorAttributesDialog {
  }
  MenuPreset CRF_AdminMenu {
   Layout "{EC85C0A243D90BB7}UI/layouts/Menus/PauseMenu/AdminMenu.layout"
   ActionContext "MenuWithEditorContext"
   Class "CRF_AdminMenu"
  }
  MenuPreset CRF_PreviewMenu {
   Layout "{024AB272759D649A}UI/Phases/Briefing.layout"
   ActionContext "BriefingContext"
   Class "CRF_PreviewMenuUI"
  }
  MenuPreset CRF_SlottingMenu {
   Layout "{FAADCD3D5A12A93B}UI/Phases/Slotting.layout"
   ActionContext "SlottingContext"
   Class "CRF_SlottingMenuUI"
  }
  MenuPreset CRF_SpectatorMenu {
   Layout "{BDC0570417BFB1EA}UI/Spectator/SpectatorHUD.layout"
   ActionContext "SpectatorContext"
   Class "CRF_SpectatorMenuUI"
  }
  MenuPreset CRF_AARMenu {
   Layout "{51E2BFEBE0765F3C}UI/Phases/AAR.layout"
   ActionContext "AARContext"
   Class "CRF_AARMenuUI"
  }
  MenuPreset CRF_RespawnMenu {
   Layout "{FDCDD64F28A1B925}UI/Respawn/CRF_Respawn.layout"
   ActionContext "SpectatorContext"
   Class "CRF_RespawnMenu"
  }
  MenuPreset CRF_CharacterLoading {
   Layout "{0AF7559B6D2A1B2C}UI/layouts/Menus/Common/Loading_Character.layout"
   Class "CRF_CharacterLoading"
  }
  MenuPreset CRF_GungameStart {
   Layout "{63AEAB1379014F00}UI/layouts/HUD/GunGame/GameStart.layout"
   Class "CRF_GungameStart"
  }
  MenuPreset CRF_GunGameEnd {
   Layout "{3022F2F62A518917}UI/layouts/HUD/GunGame/GameEnd.layout"
   Class "CRF_GunGameEnd"
  }
 }
}