CRF_GearScriptConfig {
 m_FactionName "Racists"
 m_FactionIcon "{740377C70AF5277A}CRF Images/Pie_sorryIKilledTheServer.edds"
 m_FactionIdentity "{93C4AAA0496F0B42}Configs/Identities/CRF_CharacterIdentity_American.conf"
 m_FactionWeapons CRF_Weapons "{670B63DE31E18542}" {
 }
 m_DefaultFactionGear CRF_Default_Gear "{670B63DE31E18578}" {
  m_bEnableLeadershipBinoculars 0
  m_bEnableAssistantBinoculars 0
  m_DefaultMedicMedicalItems {
   CRF_Inventory_Item "{670B63DE31E1857D}" {
    m_sItemPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
    m_iItemCount 10
   }
   CRF_Inventory_Item "{670B63DE31E18563}" {
    m_sItemPrefab "{80E75A71C29190DB}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_USSR_01.et"
    m_iItemCount 3
   }
   CRF_Inventory_Item "{670B63DE31E18562}" {
    m_sItemPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
    m_iItemCount 6
   }
   CRF_Inventory_Item "{670B63DE31E18561}" {
    m_sItemPrefab "{5B2FD067D70C1E8F}Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et"
    m_iItemCount 6
   }
   CRF_Inventory_Item "{670B63DE31E18560}" {
    m_sItemPrefab "{527D7C5D2E476BDC}Prefabs/Items/Medicine/SalineBag_01/SalineBag_USSR_01.et"
    m_iItemCount 5
   }
   CRF_Inventory_Item "{670B63DE31E18567}" {
    m_sItemPrefab "{21EF98BFC1EB3793}Prefabs/Items/Equipment/Kits/MedicalKit_01/MedicalKit_01_USSR.et"
    m_iItemCount 1
   }
  }
  m_DefaultClothing {
   CRF_Clothing "{670B63DE31E18566}" {
    m_iClothingType HEADGEAR
    m_ClothingPrefabs {
     "{6B2256EBB8E267DD}Prefabs/Characters/HeadGear/Hat_Knitted_01/Hat_Knitted_01_blue.et"
    }
   }
   CRF_Clothing "{670B63DE31E18565}" {
    m_iClothingType SHIRT
    m_ClothingPrefabs {
     "{6A3F994EFFE22995}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Shirt_Turtleneck_01_DarkBlue.et"
    }
   }
   CRF_Clothing "{670B63DE31E1E22D}" {
    m_iClothingType PANTS
    m_ClothingPrefabs {
     "{5A8C9A020BD7ABA6}Prefabs/Characters/Uniforms/Pants_Trousers_01/Pants_Trousers_01_DarkGrey.et"
    }
   }
   CRF_Clothing "{670B63DE31E1E223}" {
    m_iClothingType BOOTS
    m_ClothingPrefabs {
     "{DAAFD15478BDE1C3}Prefabs/Characters/Footwear/CombatBoots_US_01.et"
    }
   }
   CRF_Clothing "{670B63DE4BD9CB0D}" {
    m_iClothingType BACKPACK
    m_ClothingPrefabs {
     "{CE832B86D234AD62}Prefabs/Items/Equipment/Backpacks/CRF_Backpack_Invisable.et"
    }
   }
  }
  m_DefaultInventoryItems {
   CRF_Inventory_Item "{670B63DE31E1E2C0}" {
    m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
    m_iItemCount 1
   }
   CRF_Inventory_Item "{670B63DE4D16B385}" {
    m_sItemPrefab "{40DA20C161380A66}Prefabs/Weapons/Grenades/Snowball.et"
    m_iItemCount 200
   }
  }
 }
 m_CustomFactionGear CRF_Custom_Gear "{670B63DE31E1E2C5}" {
  m_RolesToSetCustomGear {
   CRF_Role_Custom_Gear "{670B63DA207C35E6}" {
    m_Role TEAM_LEAD
    m_sRoleName "Snowballer"
   }
  }
 }
}