SCR_MissionHeader : "{3D094352621EA88C}Missions/CRF_BaseMissionConfig.conf" {
 World "{58974D0100783976}Worlds/CCO22.ent"
 m_sName "CCO22 - Sainte-Mère-Église"
 m_sAuthor "Salami"
 m_sDescription ""
 m_sGameMode "CCO"
 m_sTerrainName "Normandy"
}