SCR_MissionHeader {
 World "{5FAC091F12225580}Worlds/COALobby/Rostov/PipeBombDream.ent"
 m_sName "CRF S&D94 Pipe Bomb Dream"
 m_sAuthor "fluff_"
 m_sDescription "FIA giddy up and go attack soviet rahhh"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "S&D"
 m_iPlayerCount 94
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Rostov"
}