SCR_MissionHeader : "{3D094352621EA88C}Missions/CRF_BaseMissionConfig.conf" {
 m_sName "CRF S&D97 Gentle Into That Good Night"
 m_sAuthor "Salami"
 m_sDescription "Do not go gentle into that good night,"\
 "Old age should burn and rave at close of day;"\
 "Rage, rage against the dying of the light."
 m_sGameMode "Search And Destroy"
 m_iPlayerCount 97
 m_sTerrainName "Aneropia"
}