SCR_MissionHeader {
 World "{31F55A1698DEC11E}Worlds/COALobby/Ruha/COOPBridge.ent"
 m_sName "CRF CO47 Bridge Ruha"
 m_sAuthor "tanaKa"
 m_sDescription "Company Session"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Ruha"
}