SCR_MissionHeader {
 World "{8E982D0CFCEF356F}Worlds/COALobby/Gogland/Rush_TiptoTip.ent"
 m_sName "CRF RUSH93 Tip to Tip"
 m_sAuthor "tanaKa-"
 m_sDescription "It's officially Rush. For real."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "RUSH"
 m_iPlayerCount 93
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Gogland"
}