SCR_MissionHeader {
 World "{827C2D3DB0C781F5}Worlds/COALobby/Denali/Njpatman_COOP_SnatchAndGrab.ent"
 m_sName "CRF CO50 Snatch And Grab"
 m_sAuthor "Njpatman"
 m_sDescription "Destroy The Transmitters, Secure The Intel, Dont Die."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 2
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Denali"
}