SCR_MissionHeader : "{3D094352621EA88C}Missions/CRF_BaseMissionConfig.conf" {
 World "{73023814DB3F4418}Worlds/COALobby/Hamland/Rand_COOP_MakinBacon.ent"
 m_sName "CRF COOP54 MakinBacon"
 m_sAuthor "RandAlThor"
 m_sDescription "Russian forces secure British port city"
 m_sGameMode "COOP"
 m_iPlayerCount 54
}