SCR_MissionHeader {
 World "{7EC607D936D65DA2}Worlds/COALobby/Eden/Snatch.ent"
 m_sName "CRF CO30 Snatch"
 m_sAuthor "tanaKa"
 m_sDescription "ION SF teams are dispatched to snatch a political VIP"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}