SCR_MissionHeader {
 World "{E9E50D40CA5D6A7B}Worlds/COALobby/Chernarus/Haystack.ent"
 m_sName "CRF CH92 Haystack"
 m_sAuthor "tanaKa-"
 m_sDescription "Soviet air assault"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "CH"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}