SCR_MissionHeader {
 World "{417AE39B978EF935}Worlds/COALobby/Eden/Sneak.ent"
 m_sName "CRF HVT93 False Gambit"
 m_sAuthor "tanaKa-"
 m_sDescription "Soviet forces scramble to hunt down a downed NATO C130 crew"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "HVT"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}