SCR_MissionHeader {
 World "{C8FB76208D2A0AC9}Worlds/COALobby/Aneropia/powerplant.ent"
 m_sName "CRF CO54 Powerplant"
 m_sAuthor "tanaKa-"
 m_sDescription "\"Garlic is inherently spicy\" - mystrium 2025"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Aneropia"
}