SCR_MissionHeader {
 World "{CB4803DC86EB3685}Worlds/COALobby/Chernarus/ValleyVibes.ent"
 m_sName "CRF CQ92 Three Valleys"
 m_sAuthor "tanaKa-"
 m_sDescription "An invading western force attempts to push inland in Chernarus"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "<Mode>"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}