SCR_MissionHeader {
 World "{46B69853F6DE308B}Worlds/COALobby/Eden/FanServ_CoOp_StormingOut.ent"
 m_sName "CRF CO52 Storming Out"
 m_sAuthor "FanServ"
 m_sDescription "US forces must hold Montignac in a storm"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 18
 m_iMapMarkerLimitPerPlayer 120
}