SCR_MissionHeader {
 World "{E3D0F881BF76A12E}Worlds/COALobby/Eden/subArma.ent"
 m_sName "CRF_SPCL97_You Have My Word"
 m_sAuthor "fluff"
 m_sDescription "Do hostage negotiations ever really go down according to plan?"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "SPCL"
 m_iPlayerCount 128
 m_iStartingHours 6
 m_iStartingMinutes 15
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Eden"
}