SCR_MissionHeader {
 World "{90BAABCBE01E7E74}Worlds/COALobby/Zarichne/COOP_pressure.ent"
 m_sName "CRF CO49 Pressure"
 m_sAuthor "tanaKa"
 m_sDescription "Key infrastructure"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_eGME_GlobalAISkill REGULAR
 m_sTerrainName "Zarichne"
}