SCR_MissionHeader {
 World "{8F9D0C1741592E78}Worlds/COALobby/Ruha/Njpatman_COOP_HeliTakedown.ent"
 m_sName "CRF CO45 HeliTakedown"
 m_sAuthor "Njpatman"
 m_sDescription "US Motorized Infantry take down a local USSR Helicopter Port and Headquarters"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Ruha"
}