SCR_MissionHeader {
 World "{88276B9A8D221A1B}Worlds/COALobby/Ruha/TTGBITN.ent"
 m_sName "CRF VIP 93 Things That Go Bump in the Night"
 m_sAuthor "fluff"
 m_sDescription "CDF specops rescue a cabinet member from guerillas holed up in a sawmill turned fortress."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "VIP"
 m_iPlayerCount 93
 m_iStartingHours 1
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Ruha"
}