SCR_MissionHeader {
 World "{990278E980D1A91B}Worlds/COALobby/Chernarus/RadioZenit.ent"
 m_sName "CRF RUSH92 Radio Zenit"
 m_sAuthor "tanaKa"
 m_sDescription "Man what is all that spicy rain"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "Rush"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}