SCR_MissionHeader : "{3D094352621EA88C}Missions/CRF_BaseMissionConfig.conf" {
 World "{88A0E1411F5320AA}Worlds/COALobby/Vietnam/Rand_S&D_MorningRaid.ent"
 m_sName "CRF S&D89 Morning Raid"
 m_sAuthor "RandAlThor"
 m_sDescription "PAVN Conduct a morning raid"
 m_sGameMode "S&D"
 m_iPlayerCount 89
 m_sTerrainName "Vietnam"
}