SCR_MissionHeader {
 World "{0E7C947071CF9399}Worlds/COALobby/Zimnitrita/campaign-b2.ent"
 m_sName "CRF Campaign B2"
 m_sAuthor "tanaKa"
 m_sDescription "The Liberation Of Zimnitrita"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "RUSH"
 m_iPlayerCount 128
 m_bMapMarkerEnableDeleteByAnyone 1
 m_iMapMarkerLimitPerPlayer 20
 m_sTerrainName "Zimnitrita"
}