SCR_MissionHeader {
 World "{13664D0C626F49B4}Worlds/COALobby/Gogland/trippin.ent"
 m_sName "CRF CH96 Trippin"
 m_sAuthor "tanaKa-"
 m_sDescription "A Russian Spetsnaz team attempts to confront a FIA cell"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "CH"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}