SCR_MissionHeader {
 World "{10DA4DD2E6A26A16}Worlds/COALobby/Gogland/FullEnglish.ent"
 m_sName "Full English"
 m_sAuthor "fluff_"
 m_sDescription "Gogland Search and destroy"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "Search and Destroy"
 m_iPlayerCount 89
 m_iMapMarkerLimitPerPlayer 120
}