SCR_MissionHeader {
 World "{0CBFEAB7B45CF04A}Worlds/COALobby/Rostov/CassYoko_s&d_ShowOfForce.ent"
 m_sName "CRF_S&D_113_Show of Force"
 m_sAuthor "CassYoko"
 m_sDescription "A Search and destroy mission in Rostov"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "S&D"
 m_iPlayerCount 113
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}