SCR_MissionHeader {
 World "{DEE2B608B3BB6233}Worlds/COALobby/Denali/Njpatman_COOP_SearchParty.ent"
 m_sName "CRF CO53 Search Party"
 m_sAuthor "Njpatman"
 m_sDescription "US backed insurgents in the area must be destroyed to ensure a peaceful and prosperous region for the soviet union."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 2
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Denali"
}