SCR_MissionHeader {
 World "{39D66F557CF61CCF}Worlds/COALobby/Ruha/Njpatman_COOP_ThunderRun.ent"
 m_sName "CRF CO50 Thunder Run"
 m_sAuthor "Njpatman"
 m_sDescription "Take and secure the russian held power plant, then dig in for russian counter attack"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 2
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Ruha"
}