SCR_MissionHeader {
 World "{74948D606DAAD76C}Worlds/COALobby/Denali/flashpoint57.ent"
 m_sName "CRF Rush94 Flashpoint57"
 m_sAuthor "fluff_"
 m_sDescription "The Soviet invasion of Alaska cannot go on for too long..."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "Rush"
 m_iPlayerCount 94
 m_iStartingHours 21
 m_iMapMarkerLimitPerPlayer 300
 m_sTerrainName "Denali"
}