SCR_MissionHeader {
 World "{C9D835069701234A}Worlds/COALobby/Arland/Rush.ent"
 m_sName "CRF RUSH92 Rush (Night)"
 m_sAuthor "tanaKa"
 m_sDescription "Destroy 2 MCOMS to proceed"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "92"
 m_iPlayerCount 128
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 23
 m_iMapMarkerLimitPerPlayer 120
}