SCR_MissionHeader {
 World "{D823223F45C9F310}Worlds/COALobby/Bearland/Dirt.ent"
 m_sName "CRF RUSH86 Dirt"
 m_sAuthor "tanaKa-"
 m_sDescription "Bearland rebels take on a modern army invasion"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "RUSH"
 m_iPlayerCount 86
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Bearland"
}