SCR_MissionHeader {
 World "{F4598846CAFF585D}Worlds/COALobby/Serhiivka/BananaGuards.ent"
 m_sName "CRF SPCL105 Banana Guards"
 m_sAuthor "tanaKa-"
 m_sDescription "Protect the bananas at all cost"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "SPCL"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}