SCR_MissionHeader : "{3D094352621EA88C}Missions/CRF_BaseMissionConfig.conf" {
 World "{0A67915C0C9BD56F}Worlds/COALobby/RingKollen/SAL_RAID_SuddenThrust.ent"
 m_sName "CRF Raid88 Sudden Thrust"
 m_sAuthor "Salami"
 m_sDescription "A Royal Marine Platoon raids a Russian supply depot."
 m_sGameMode "Raid"
 m_iPlayerCount 88
 m_sTerrainName "Ringkollen"
}