SCR_MissionHeader {
 World "{66F2DDDB8BD3C200}Worlds/COALobby/Vietnam/FanServ_VIP_HeartOfDarkness.ent"
 m_sName "CRF VIP98 Heart of Darkness"
 m_sAuthor "FanServ"
 m_sDescription "A rogue US Army colonel must be eliminated by a MACV-SOG team."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "VIP"
 m_iPlayerCount 98
 m_iStartingHours 18
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Khanh Trung"
}