SCR_MissionHeader {
 World "{D46E4506BE7E6593}Worlds/COALobby/BadOrb/Harry_TVT_WITP.ent"
 m_sName "CRF CH98 Winds In The Pines"
 m_sAuthor "Harry"
 m_sDescription "Presents from the sky"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "Cache Hunt"
 m_iPlayerCount 98
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "BadOrb"
}