SCR_MissionHeader {
 World "{5E0044A2B0740348}Worlds/COALobby/Takistan/Harry_TVT_LowRiders.ent"
 m_sName "CRF HVT94 Low Riders"
 m_sAuthor "Harry"
 m_sDescription "Ambush survivors try to hold out."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "HVT"
 m_iPlayerCount 89
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Takistan"
}