SCR_MissionHeader {
 World "{CED7E64C75A600EA}Worlds/COALobby/Ringkollen/Harry_TVT_AmongTheLeaves.ent"
 m_sName "CRF Rush99 Among The Leaves"
 m_sAuthor "Harry"
 m_sDescription "There's bad blood in Valentine's Gang."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "Rush"
 m_iPlayerCount 99
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Ringkollen"
}