SCR_MissionHeader {
 World "{D6A86D602D9A7F21}Worlds/COALobby/Kolguyev/Harry_TVT_Hayfever.ent"
 m_sName "CRF HVT88 Hayfever"
 m_sAuthor "Harry"
 m_sDescription "Someone's calling themselves FOXHOUND again..."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "High Value Target"
 m_iPlayerCount 88
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Kolguyev"
}