SCR_MissionHeader {
 World "{1A37272735E2E9D8}Worlds/COALobby/Novka/Harry_TVT_MountainPass.ent"
 m_sName "CRF  SE99 Mountain Pass"
 m_sAuthor "Harry"
 m_sDescription "The mountains of Novka are beautiful this time of year."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "Supply Extract"
 m_iPlayerCount 99
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Novka"
}