SCR_MissionHeader {
 World "{FD8CF837E9044B49}Worlds/COALobby/Kolguyev/Harry_TVT_Consign.ent"
 m_sName "CRF Evac96 Consigned"
 m_sAuthor "Harry"
 m_sDescription "What did they find in the tunnels?"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "Evacuation"
 m_iPlayerCount 96
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Kolguyev"
}