SCR_MissionHeader {
 World "{936BB211DAE3F4DB}Worlds/COALobby/Rostov/Harry_TVT_SleepingDogs.ent"
 m_sName "CRF HVT113 Sleeping Dogs"
 m_sAuthor "Harry"
 m_sDescription "Opfor is hunting down an HVT"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "HVT"
 m_iPlayerCount 113
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}