SCR_MissionHeader {
 World "{0FB6A14259C31389}Worlds/COALobby/Kunar/Harry_TVT_CliffSideRDV.ent"
 m_sName "CRF VIP88 Cliff Side RDV"
 m_sAuthor "Harry"
 m_sDescription "No one would kill a civ...right?"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "VIP"
 m_iPlayerCount 88
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}