SCR_MissionHeader {
 World "{F0046F0C3A02D591}Worlds/COALobby/Gulfcoast/Harry_SPCL_VictoryAndHonor.ent"
 m_sName "CRF SPCL86 Victory and Honor"
 m_sAuthor "Harry"
 m_sDescription "Opfor tries to move a tank througha an island full of madmen."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "SPCL"
 m_iPlayerCount 86
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}