SCR_MissionHeader {
 World "{38C99A31DECBB6BE}Worlds/COALobby/Arland/Trist_SPCL_JustAnotherRally.ent"
 m_sName "CRF SPCL80 Just Another Rally"
 m_sAuthor "Trist"
 m_sDescription "This rally came to me in a dream."
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "SPCL"
 m_iPlayerCount 80
 m_iStartingHours 6
 m_iStartingMinutes 45
 m_iMapMarkerLimitPerPlayer 120
}