SCR_MissionHeader : "{3D094352621EA88C}Missions/CRF_BaseMissionConfig.conf" {
 World "{52F3D5A2BDBFDC3F}Worlds/COALobby/Rostov/Trist_GetSomme_SPCL.ent"
 m_sName "CRF SPCL98 Get Somme"
 m_sAuthor "Trist"
 m_sDescription "Rejects with very little, fight in the trenches for even less."
 m_sGameMode "SPCL"
 m_iPlayerCount 98
 m_iStartingHours 19
}