SCR_MissionHeader : "{3D094352621EA88C}Missions/CRF_BaseMissionConfig.conf" {
 World "{FF747AC6F4C33B05}Worlds/COALobby/Eden/Trist_SPCL_GangsOfEden.ent"
 m_sName "CRF SPCL94 Gangs Of Eden"
 m_sAuthor "Trist"
 m_sDescription "Looting/Infection TVT SPCL. Police grow in number on death of gangs."
 m_sGameMode "SPCL"
 m_iPlayerCount 94
 m_iStartingHours 20
 m_iStartingMinutes 30
 m_sTerrainName "Eden"
}