SCR_MissionHeader {
 World "{FE5DB35657715E14}Worlds/COALobby/RingKollen/Yoko_HVT_Castling.ent"
 m_sName "CRF HVT93 Castling"
 m_sAuthor "CassYoko"
 m_sDescription "0-0"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "High Value Target"
 m_iPlayerCount 93
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Ringkollen"
}