SCR_MissionHeader {
 World "{E9CB2E546CA08F5D}Worlds/COALobby/Kolguyev/Yoko_TVT_SendIt.ent"
 m_sName "CRF S&D96 Send It"
 m_sAuthor "CassYoko"
 m_sDescription "Thunder Run?"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "Search And Destroy"
 m_iPlayerCount 96
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Kolguyev"
}