SCR_MissionHeader {
 World "{DC853D4079BE1175}Worlds/COALobby/Novka/Yoko_TVT_Prototype.ent"
 m_sName "CRF Escort 90 Prototype"
 m_sAuthor "CassYoko"
 m_sDescription "What is that thing?"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "Escort"
 m_iPlayerCount 90
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
 m_sTerrainName "Novka"
}