CRF_CharacterIdentity {
 m_VisualIdentityArray {
  CRF_Character_Visual_Identity "{69CEE521D2BE4A50}" {
   m_Head "{68A0EC2B1FAEDC65}Prefabs/Characters/Heads/Head_AfricanHead_01.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{69CEE521D2BE4A59}" {
   m_Head "{04F4D8CBA36A534C}Prefabs/Characters/Heads/Head_AfricanHead_02.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{69CEE521D2BE4A58}" {
   m_Head "{E1689432AF8FC420}Prefabs/Characters/Heads/Head_AfricanHead_03.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{69CEE521D2BFA15A}" {
   m_Head "{F8ED1678144C1013}Prefabs/Characters/Heads/Head_AfricanHead_h.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{69CEE521D2BFA164}" {
   m_Head "{7A743FD3AA9E0868}Prefabs/Characters/Heads/Head_Barklem.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
 }
 m_SoundIdentityArray {
  CRF_Character_Sound_Identity "{69CEE521D2BF2C3C}" {
   m_VoiceID 101
  }
  CRF_Character_Sound_Identity "{69CEE521D2BF2C3D}" {
   m_VoiceID 101
   m_VoicePitch 0.8
  }
  CRF_Character_Sound_Identity "{69CEE521D2BF2C3E}" {
   m_VoiceID 101
   m_VoicePitch -1
  }
  CRF_Character_Sound_Identity "{69CEE521D2BF5F19}" {
   m_VoiceID 102
  }
  CRF_Character_Sound_Identity "{69CEE521D2BF5F18}" {
   m_VoiceID 102
   m_VoicePitch 0.9
  }
  CRF_Character_Sound_Identity "{69CEE521D2BF5F17}" {
   m_VoiceID 102
   m_VoicePitch -1
  }
 }
}