CRF_CharacterIdentity {
 m_VisualIdentityArray {
  CRF_Character_Visual_Identity "{69CEE5213188B596}" {
   m_Head "{27D3A7FF51948ED5}Prefabs/Characters/Heads/Head_AfricanHead_01_camo.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{69CEE5213188B58F}" {
   m_Head "{0B85217ED2873009}Prefabs/Characters/Heads/Head_AfricanHead_02_camo.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{69CEE5213188B58E}" {
   m_Head "{0E70E2B939D5CABF}Prefabs/Characters/Heads/Head_AfricanHead_03_camo.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{69CEE521318B7633}" {
   m_Head "{151D478228758DF1}Prefabs/Characters/Heads/Head_AfricanHead_h_camo.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
  CRF_Character_Visual_Identity "{69CEE521318B7637}" {
   m_Head "{9DF0FB8F58FCC7F0}Prefabs/Characters/Heads/Head_Barklem_camo.et"
   m_Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
 }
 m_SoundIdentityArray {
  CRF_Character_Sound_Identity "{69CEE521318B7634}" {
   m_VoiceID 101
  }
  CRF_Character_Sound_Identity "{69CEE521318B7635}" {
   m_VoiceID 101
   m_VoicePitch 0.8
  }
  CRF_Character_Sound_Identity "{69CEE521318B0951}" {
   m_VoiceID 101
   m_VoicePitch -1
  }
  CRF_Character_Sound_Identity "{69CEE521318B095E}" {
   m_VoiceID 102
  }
  CRF_Character_Sound_Identity "{69CEE521318B095F}" {
   m_VoiceID 102
   m_VoicePitch 0.9
  }
  CRF_Character_Sound_Identity "{69CEE521318B095C}" {
   m_VoiceID 102
   m_VoicePitch -1
  }
 }
}