CRF_GearScriptConfig {
 m_FactionName "Hunters"
 m_FactionIcon "{56B63D9413011A75}UI/Images/Coalition/Coalition.edds"
 m_Rifles {
  CRF_Weapon_Class "{62C61C175D3AEE4E}" {
   m_Weapon "{24FFA508861139C9}Prefabs/Weapons/Rifles/L42A1/Rifle_L8.et"
   m_Attachments {
    ""
   }
   m_MagazineArray {
    CRF_Magazine_Class "{631027AC9E4368A5}" {
     m_Magazine "{4F4439BAA80A7A66}Prefabs/Weapons/Magazines/Magazine_762x51_L42a1_10rnd_Base.et"
     m_MagazineCount 1
    }
   }
  }
 }
 m_Pistols {
  CRF_Weapon_Class "{644A2D5BA832196C}" {
   m_Weapon "{D9889FC9DB8C06C0}Prefabs/Weapons/Handguns/HiPower/Handgun_HiPower.et"
   m_MagazineArray {
    CRF_Magazine_Class "{644A2D5BB56F5E67}" {
     m_Magazine "{1E7D876C06089E21}Prefabs/Weapons/Magazines/Magazine_9x19_HiPower_13rnd_Ball.et"
     m_MagazineCount 1
    }
   }
  }
 }
 m_DefaultClothing {
  CRF_Clothing "{62C61C161D7825A6}" {
   m_iClothingType HEADGEAR
   m_ClothingPrefabs {
    "{CF15283AEC4EE934}Prefabs/Characters/HeadGear/Hat_Panama_Soviet/Hat_Panama_Soviet_01_base.et"
    "{793EEE2C133176F9}Prefabs/Characters/HeadGear/Hat_Panama_Soviet/Hat_Panama_Soviet_01_v1.et"
   }
  }
  CRF_Clothing "{62C61C161D7825A2}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{50F8B1F928F93ABD}Prefabs/Characters/Uniforms/Shirt_Turtleneck_01/Shirt_Turtleneck_01_beige.et"
    "{9F546CCA2582D16F}Prefabs/Characters/Uniforms/Jacket_M88.et"
    "{D262D2102B9931C6}Prefabs/Characters/Uniforms/Jacket_M88_rolledup.et"
    "{E44990162EBC47B7}Prefabs/Characters/Uniforms/Jacket_M88_base.et"
   }
  }
  CRF_Clothing "{62C61C161D7825AD}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{DCF980831E880F6A}Prefabs/Characters/Uniforms/Pants_M88.et"
   }
  }
  CRF_Clothing "{62C61C161D7825A9}" {
   m_iClothingType BOOTS
   m_ClothingPrefabs {
    "{203EEA924B049EF1}Prefabs/Characters/Footwear/JungleBoots_01/JungleBoots_01.et"
   }
  }
 }
 m_bEnableLeadershipBinoculars 0
 m_bEnableAssistantBinoculars 0
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{63120CF9923B9A60}" {
   m_sItemPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{63120CF946F2A7EE}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{644A2D440E59D0D0}" {
   m_sItemPrefab "{3A421547BC29F679}Prefabs/Items/Equipment/Flashlights/Flashlight_MX991/Flashlight_MX991.et"
   m_iItemCount 1
  }
 }
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{673A7339FAD73F2C}" {
   m_sItemPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
   m_iItemCount 4
  }
  CRF_Inventory_Item "{673A7339FAF434B1}" {
   m_sItemPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
   m_iItemCount 2
  }
 }
}