CRF_GearScriptConfig {
 m_FactionName "Pharaoh"
 m_FactionIcon "{D5BF7BD3D5406B1E}Assets/Materials/Flags/Factions/data/Flag_Test_Curse_Of_Ra.edds"
 m_FactionIdentity "{E13982CDA81E8F0C}Configs/Identities/Asia/CRF_CharacterIdentity_Asian.conf"
 m_DefaultClothing {
  CRF_Clothing "{68731CE62D33A0E1}" {
   m_iClothingType HEADGEAR
   m_ClothingPrefabs {
    "{63B7E7E70EE8FB54}Prefabs/Characters/HeadGear/Hat_FlatCap_01/TurbanC03.et"
   }
  }
  CRF_Clothing "{68731CE62D33A0E6}" {
   m_iClothingType SHIRT
  }
  CRF_Clothing "{68731CE62D33A0E4}" {
   m_iClothingType PANTS
  }
  CRF_Clothing "{68731CE62D33A0E5}" {
   m_iClothingType BOOTS
  }
  CRF_Clothing "{68742CCA31F0484E}" {
   m_iClothingType BACKPACK
   m_ClothingPrefabs {
    "{CE832B86D234AD62}Prefabs/Items/Equipment/Backpacks/CRF_Backpack_Invisable.et"
   }
  }
 }
 m_bEnableLeadershipBinoculars 0
 m_bEnableAssistantBinoculars 0
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{68731CE62D33A0FB}" {
   m_sItemPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{68731CE62D33A0F8}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{68742EBAE79CFE42}" {
   m_sItemPrefab "{3343A055A83CB30D}Prefabs/Weapons/Grenades/M18/Smoke_M18_Red.et"
   m_iItemCount 2
  }
 }
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{68731CE62D33A0F9}" {
   m_sItemPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
   m_iItemCount 4
  }
  CRF_Inventory_Item "{68731CE62D33A0FE}" {
   m_sItemPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{68731CE62D33A0FF}" {
   m_sItemPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   m_iItemCount 2
  }
 }
}