CRF_GearScriptConfig {
 m_FactionName "Guardians"
 m_FactionIcon "{D5BF7BD3D5406B1E}Assets/Materials/Flags/Factions/data/Flag_Test_Curse_Of_Ra.edds"
 m_FactionIdentity "{E13982CDA81E8F0C}Configs/Identities/Asia/CRF_CharacterIdentity_Asian.conf"
 m_Rifles {
  CRF_Weapon_Class "{62C61C175D3AEE4E}" {
   m_Weapon "{CD0CEFF39B090D79}Prefabs/Weapons/Rifles/M16/Variants/LondonBathtub_M16_Bayonet.et"
  }
 }
 m_DefaultClothing {
  CRF_Clothing "{62C61C161D7825A6}" {
   m_iClothingType HEADGEAR
   m_ClothingPrefabs {
    "{56EEA6B0E5BA4404}Prefabs/Characters/HeadGear/Helmet_OPSCORE/Helmet_OPSCORE_XP_Black_AMP_Turban.et"
   }
  }
  CRF_Clothing "{62C61C161D7825A2}" {
   m_iClothingType SHIRT
   m_ClothingPrefabs {
    "{318BF42CA23BDAAD}Prefabs/Characters/Uniforms/TakShirts/Chilaba01.et"
    "{5DDFC0CC1EFF5584}Prefabs/Characters/Uniforms/TakShirts/Chilaba02.et"
    "{5DDFC0CC1EFF5584}Prefabs/Characters/Uniforms/TakShirts/Chilaba02.et"
   }
  }
  CRF_Clothing "{62C61C161D7825AD}" {
   m_iClothingType PANTS
   m_ClothingPrefabs {
    "{E34178781383EF6D}Prefabs/Characters/Uniforms/TakPants/TakPant03.et"
    "{3BE911B96A0AF131}Prefabs/Characters/Uniforms/TakPants/TakPant05.et"
    "{B22169A0DA2BE974}Prefabs/Characters/Uniforms/TakPants/TakPant07.et"
   }
  }
  CRF_Clothing "{62C61C161D7825A9}" {
   m_iClothingType BOOTS
  }
 }
 m_DefaultInventoryItems {
  CRF_Inventory_Item "{63120CF962341D2D}" {
   m_sItemPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{63120CF9621622F0}" {
   m_sItemPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{6874078CDD278760}" {
   m_sItemPrefab "{3343A055A83CB30D}Prefabs/Weapons/Grenades/M18/Smoke_M18_Red.et"
   m_iItemCount 1
  }
  CRF_Inventory_Item "{687A7E1CDBF6E477}" {
   m_sItemPrefab "{59E0D9B5B6967152}Prefabs/Items/Equipment/Nightvision/PVS31/NVG_PVS31_WP.et"
   m_iItemCount 1
  }
 }
 m_InfantryMedicalItems {
  CRF_Inventory_Item "{673A73271C8EEEC4}" {
   m_sItemPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
   m_iItemCount 4
  }
  CRF_Inventory_Item "{673A73271E167A07}" {
   m_sItemPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
   m_iItemCount 2
  }
  CRF_Inventory_Item "{673A732706352311}" {
   m_sItemPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   m_iItemCount 2
  }
 }
}