CRF_SlottingGroup {
 m_sCallsign "1-1"
 m_aSlots {
  SQUAD_LEAD
  MEDIC
  TEAM_LEAD
  AUTOMATIC_RIFLEMAN
  ASSISTANT_AUTOMATIC_RIFLEMAN
  TEAM_LEAD
  RIFLEMAN_ANTITANK
  RIFLEMAN_ANTITANK
  RIFLEMAN_DEMO
 }
}