CVON_FreqConfig {
 m_aPresetGroupFrequencyContainers {
  CVON_GroupFrequencyContainer "{664376B222BB8A97}" {
   m_aGroupNames {
    "COY"
   }
   m_aLRFrequencies {
    "FIRES"
   }
  }
  CVON_GroupFrequencyContainer "{690EECCB4BE7A84D}" {
   m_aGroupNames {
    "SNIPER"
   }
   m_aSRFrequencies {
    "PLATOON"
   }
   m_aLRFrequencies {
    "LOGI"
   }
  }
 }
}