CRF_CharacterIdentity {
 m_VisualIdentityArray {
  CRF_Character_Visual_Identity "{66780A8218FD360E}" {
   m_Head "{3B473755F8A85D65}Prefabs/Characters/Heads/Head_GreekHead_A3_04.et"
   m_Body "{5EE1CAC3D1D1AC47}Prefabs/Characters/Basebody/CharacterBasebody_Asian_01.et"
  }
 }
 m_SoundIdentityArray {
  CRF_Character_Sound_Identity "{66780A83FE9DDB04}" {
   m_VoiceID 101
  }
  CRF_Character_Sound_Identity "{66780A83FE9DDB06}" {
   m_VoiceID 101
   m_VoicePitch 0.8
  }
  CRF_Character_Sound_Identity "{66780A83FE9DDB08}" {
   m_VoiceID 101
   m_VoicePitch -1
  }
  CRF_Character_Sound_Identity "{66780A83FE9DDB09}" {
   m_VoiceID 102
  }
  CRF_Character_Sound_Identity "{66780A83FE9DDB0B}" {
   m_VoiceID 102
   m_VoicePitch 0.9
  }
  CRF_Character_Sound_Identity "{66780A83FE9DDB0C}" {
   m_VoiceID 102
   m_VoicePitch -1
  }
 }
}