SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{1DE2CFFF2775C07C}Prefabs/Compositions/Misc/FreeRoamBuilding/Rallypoints/BLUFOR/E_CRF_RallyPointBuildable_BLUFOR.et"
  "{6F48F93E3C7401EB}Prefabs/Compositions/Misc/FreeRoamBuilding/Rallypoints/OPFOR/E_CRF_RallyPointBuildable_OPFOR.et"
 }
}