StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60F896A34D37E060}" {
   Id "#Author_Coalition"
   Target_en_us "Coalition"
   Target_fr_fr "Coalition"
   Target_it_it "Coalition"
   Target_de_de "Coalition"
   Target_es_es "Coalition"
   Modified 1626905417
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0B88B7B4C}" {
   Id "#Coal_SS_Countdown_Cancelled"
   Target_en_us "[CRF] : Game Live Countdown Canceled!"
   Target_de_de "[CRF] : Spielstart Countdown gestoppt!"
   Modified 1626905676
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0A7205480}" {
   Id "#Coal_SS_Countdown_Started"
   Target_en_us "[CRF] : Game Live In: %1 Seconds!"
   Target_de_de "[CRF] : Spiel startet in %1 Sekunden!"
   Modified 1626905691
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0E6620551}" {
   Id "#Coal_SS_Faction_Not_Ready"
   Target_en_us "Not Ready"
   Target_de_de "Nicht bereit"
   Modified 1626905698
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0F2448B7A}" {
   Id "#Coal_SS_Faction_Readied"
   Target_en_us "[CRF] : %1 Has Readied Up a faction"
   Target_de_de "[CRF] : %1 hat eine Fraktion für bereit erklärt"
   Comment "Generic version of ready string in case a certain side/faction is not represented in the other strings"
   Modified 1626905909
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0C5CAEB3E}" {
   Id "#Coal_SS_Faction_Readied_Blufor"
   Target_en_us "[CRF] : %1 Has Readied Up Blufor"
   Target_de_de "[CRF] : %1 hat Blufor für bereit erklärt"
   Modified 1626905777
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0D88FF976}" {
   Id "#Coal_SS_Faction_Readied_Indfor"
   Target_en_us "[CRF] : %1 Has Readied Up Indfor"
   Target_de_de "[CRF] : %1 hat Indfor für bereit erklärt"
   Modified 1626905782
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0DB27AEB5}" {
   Id "#Coal_SS_Faction_Readied_Opfor"
   Target_en_us "[CRF] : %1 Has Readied Up Opfor"
   Target_de_de "[CRF] : %1 hat Opfor für bereit erklärt"
   Modified 1626905795
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0E3AF119F}" {
   Id "#Coal_SS_Faction_Ready"
   Target_en_us "Ready"
   Target_de_de "Bereit"
   Modified 1626905702
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0F0D0AD67}" {
   Id "#Coal_SS_Faction_Unreadied"
   Target_en_us "[CRF] : %1 Has Unreadied a faction"
   Target_de_de "[CRF] : %1 hat eine Fraktion für nicht bereit erklärt"
   Comment "Generic version of unreadied string in case a certain side/faction is not represented in the other strings"
   Modified 1626905895
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0C8E44A59}" {
   Id "#Coal_SS_Faction_Unreadied_Blufor"
   Target_en_us "[CRF] : %1 Has Unreadied Blufor"
   Target_de_de "[CRF] : %1 hat Blufor für nicht bereit erklärt"
   Modified 1626905824
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0CF9391A8}" {
   Id "#Coal_SS_Faction_Unreadied_Indfor"
   Target_en_us "[CRF] : %1 Has Unreadied Indfor"
   Target_de_de "[CRF] : %1 hat Indfor für nicht bereit erklärt"
   Modified 1626905831
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0CE385C91}" {
   Id "#Coal_SS_Faction_Unreadied_Opfor"
   Target_en_us "[CRF] : %1 Has Unreadied Opfor"
   Target_de_de "[CRF] : %1 hat Opfor für nicht bereit erklärt"
   Modified 1626905846
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0BC23E5A7}" {
   Id "#Coal_SS_Game_Live"
   Target_en_us "[CRF] : GAME LIVE!"
   Target_de_de "[CRF] : SPIEL STARTET!"
   Modified 1626905647
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A314B0E6AA}" {
   Id "#Coal_SS_No_Faction"
   Target_en_us "N/A"
   Target_de_de "N/A"
   Modified 1626905360
   Author "pi123"
   LastChanged "pi123"
  }
 }
}