StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60F896A34D37E060}" {
   Id "Author_Coalition"
   Target_en_us "Coalition"
   Target_fr_fr "Coalition"
   Target_it_it "Coalition"
   Target_de_de "Coalition"
   Target_es_es "Coalition"
   Modified 1627130162
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60FB7C0B6F7094F2}" {
   Id "Coal_Missions_Lobby_Assets_Title"
   Target_en_us "Assets"
   Modified 1627130165
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60FB7C0B6A1323E4}" {
   Id "Coal_Missions_Lobby_Important_Notes_Text"
   Target_en_us "'U' key opens up the lobby menu, however, this may be disabled by default and only accessible by admins."\
   ""\
   "Spectator is enabled. Upon dying, you will instantly go into spectator. Use the right side of the screen to switch your voice channel."
   Modified 1627130168
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60FB7C0B94B547A6}" {
   Id "Coal_Missions_Lobby_Important_Notes_Title"
   Target_en_us "Important Notes"
   Target_de_de "Wichtige Informationen"
   Modified 1627130171
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60FB7C0B62FA62E8}" {
   Id "Coal_Missions_Lobby_Situation_Title"
   Target_en_us "Situation"
   Target_de_de "Situation"
   Modified 1627130178
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60FB7C0BA42EC425}" {
   Id "Coal_Missions_Lobby_Welcome_Text"
   Target_en_us "This is a Reforger lobby mission on the COALITION Reforger Framework (CRF). "\
   ""\
   "If you just joined, the mission will start momentarily. If you joined after the mission started, you can go to the Lobby page at the top of your screen and select a role. If there are no roles, then you are required to spectate until next mission."\
   "If you have any questions, message an admin in the in-game chat. "
   Modified 1630682375
   Author "pi123"
   LastChanged "tanaKa"
  }
  CustomStringTableItem "{60FB7C0BA681C146}" {
   Id "Coal_Missions_Lobby_Welcome_Title"
   Target_en_us "Welcome!"
   Target_de_de "Willkommen!"
   Modified 1627130071
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60FB7C0B6750685F}" {
   Id "Coal_Missions_Lobby_WinConditions_Title"
   Target_en_us "Winning Conditions"
   Target_de_de "Missionsziele"
   Modified 1627130181
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0B88B7B4C}" {
   Id "Coal_SS_Countdown_Cancelled"
   Target_en_us "[CRF] : Game Live Countdown Canceled!"
   Target_de_de "[CRF] : Spielstart Countdown gestoppt!"
   Modified 1627130184
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0A7205480}" {
   Id "Coal_SS_Countdown_Started"
   Target_en_us "[CRF] : Game Live In:"
   Target_de_de "[CRF] : Spiel startet in:"
   Modified 1629886169
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{61261510B6F5FDE9}" {
   Id "Coal_SS_Countdown_Started_Subtext"
   Target_en_us "Any leader can toggle ready to cancel the countdown"
   Modified 1629886243
   Author "Njpatman"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60F896A0E6620551}" {
   Id "Coal_SS_Faction_Not_Ready"
   Target_en_us "Not Ready"
   Target_de_de "Nicht bereit"
   Modified 1627130190
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0F2448B7A}" {
   Id "Coal_SS_Faction_Readied"
   Target_en_us "[CRF] : Faction Ready"
   Target_de_de "[CRF] : Fraktion bereit"
   Comment "Generic version of ready string in case a certain side/faction is not represented in the other strings"
   Modified 1629886119
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60F896A0C5CAEB3E}" {
   Id "Coal_SS_Faction_Readied_Blufor"
   Target_en_us "[CRF] : BLUFOR READY"
   Target_de_de "[CRF] : BLUFOR bereit"
   Modified 1629886122
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60F896A0D88FF976}" {
   Id "Coal_SS_Faction_Readied_Indfor"
   Target_en_us "[CRF] : INDFOR READY"
   Target_de_de "[CRF] : INDFOR bereit"
   Modified 1629886124
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60F896A0DB27AEB5}" {
   Id "Coal_SS_Faction_Readied_Opfor"
   Target_en_us "[CRF] : OPFOR READY"
   Target_de_de "[CRF] : OPFOR bereit"
   Modified 1629886126
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60F896A0E3AF119F}" {
   Id "Coal_SS_Faction_Ready"
   Target_en_us "Ready"
   Target_de_de "Bereit"
   Modified 1627130205
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A0F0D0AD67}" {
   Id "Coal_SS_Faction_Unreadied"
   Target_en_us "[CRF] : Faction NOT READY"
   Target_de_de "[CRF] : Fraktion nicht bereit"
   Comment "Generic version of unreadied string in case a certain side/faction is not represented in the other strings"
   Modified 1629886098
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60F896A0C8E44A59}" {
   Id "Coal_SS_Faction_Unreadied_Blufor"
   Target_en_us "[CRF] : BLUFOR NOT READY"
   Target_de_de "[CRF] : BLUFOR nicht breit"
   Modified 1629886101
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60F896A0CF9391A8}" {
   Id "Coal_SS_Faction_Unreadied_Indfor"
   Target_en_us "[CRF] : INDFOR NOT READY"
   Target_de_de "[CRF] : INDFOR nicht breit"
   Modified 1629886103
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60F896A0CE385C91}" {
   Id "Coal_SS_Faction_Unreadied_Opfor"
   Target_en_us "[CRF] : OPFOR NOT READY"
   Target_de_de "[CRF] : OPFOR nicht breit"
   Modified 1629886106
   Author "pi123"
   LastChanged "Njpatman"
  }
  CustomStringTableItem "{60F896A0BC23E5A7}" {
   Id "Coal_SS_Game_Live"
   Target_en_us "[CRF] : GAME LIVE!"
   Target_de_de "[CRF] : SPIEL STARTET!"
   Modified 1627130155
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{60F896A314B0E6AA}" {
   Id "Coal_SS_No_Faction"
   Target_en_us "N/A"
   Target_de_de "N/A"
   Modified 1627130151
   Author "pi123"
   LastChanged "pi123"
  }
  CustomStringTableItem "{61264D4652E8FD9F}" {
   Id "Coal_SS_SafeStart_Started_Subtext"
   Target_en_us "Safestart has ended, weapons are now live!"
   Modified 1629905194
   Author "Njpatman"
   LastChanged "Njpatman"
  }
 }
}