SCR_EditorAttributeList {
 m_aAttributes {
  CRF_EnableLeadersArsenal "{687A0C66C989CF66}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{687A0C66C778745D}" {
    Name "Enable Arsenal for Leaders Only"
    Description "If Enabled only leadership slots can open arsenals"
   }
   m_CategoryConfig "{EDD16BBBE3767070}Configs/Editor/AttributeCategories/GameSettings.conf"
   m_Layout "{D0F3CE0C63A5AEBB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Checkbox.layout"
  }
 }
}