CVON_FreqConfig {
 m_aPresetGroupFrequencyContainers {
  CVON_GroupFrequencyContainer "{6642D8B19EEBA2DB}" {
   m_aGroupNames {
    "COY"
   }
   m_aSRFrequencies {
    "COYSR"
   }
   m_aLRFrequencies {
    "COY"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1F5B6AD5B}" {
   m_aGroupNames {
    "1PLT"
   }
   m_aSRFrequencies {
    "1PLTSR"
   }
   m_aLRFrequencies {
    "COY"
    "1PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1E7EDD85C}" {
   m_aGroupNames {
    "1-1"
    "Squad 1"
   }
   m_aSRFrequencies {
    "1-1"
   }
   m_aLRFrequencies {
    "PLT1"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1DAF54C5F}" {
   m_aGroupNames {
    "1-2"
    "Squad 2"
   }
   m_aSRFrequencies {
    "1-2"
   }
   m_aLRFrequencies {
    "PLT1"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1D5B2F2AE}" {
   m_aGroupNames {
    "1-3"
    "Squad 3"
   }
   m_aSRFrequencies {
    "1-3"
   }
   m_aLRFrequencies {
    "PLT1"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1D4BFA7F0}" {
   m_aGroupNames {
    "1-4"
    "Squad 4"
   }
   m_aSRFrequencies {
    "1-4"
   }
   m_aLRFrequencies {
    "PLT1"
   }
  }
 }
}