CVON_FreqConfig {
 m_aPresetGroupFrequencyContainers {
  CVON_GroupFrequencyContainer "{6642D8B19EEBA2DB}" {
   m_aGroupNames {
    "COY"
    "Company"
   }
   m_aSRFrequencies {
    "COY SR"
   }
   m_aLRFrequencies {
    "COY"
    "FIRES"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1F5B6AD5B}" {
   m_aGroupNames {
    "1PLT"
    "1st Platoon"
   }
   m_aSRFrequencies {
    "1PLT SR"
   }
   m_aLRFrequencies {
    "COY"
    "1PLT"
    "1PLT ARMOR"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1E7EDD85C}" {
   m_aGroupNames {
    "1-1"
    "Squad 1"
   }
   m_aSRFrequencies {
    "1-1"
   }
   m_aLRFrequencies {
    "1PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1DAF54C5F}" {
   m_aGroupNames {
    "1-2"
    "Squad 2"
   }
   m_aSRFrequencies {
    "1-2"
   }
   m_aLRFrequencies {
    "1PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1D5B2F2AE}" {
   m_aGroupNames {
    "1-3"
    "Squad 3"
   }
   m_aSRFrequencies {
    "1-3"
   }
   m_aLRFrequencies {
    "1PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8B1D4BFA7F0}" {
   m_aGroupNames {
    "1-4"
    "Squad 4"
   }
   m_aSRFrequencies {
    "1-4"
   }
   m_aLRFrequencies {
    "1PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D886823BBD32}" {
   m_aGroupNames {
    "2PLT"
    "2nd Platoon"
   }
   m_aSRFrequencies {
    "2PLT SR"
   }
   m_aLRFrequencies {
    "COY"
    "2PLT"
    "2PLT ARMOR"
   }
  }
  CVON_GroupFrequencyContainer "{6642D886F9262627}" {
   m_aGroupNames {
    "2-1"
    "Squad 5"
   }
   m_aSRFrequencies {
    "2-1"
   }
   m_aLRFrequencies {
    "2PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D886CF14F295}" {
   m_aGroupNames {
    "2-2"
    "Squad 6"
   }
   m_aSRFrequencies {
    "2-2"
   }
   m_aLRFrequencies {
    "2PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D886CE153723}" {
   m_aGroupNames {
    "2-3"
    "Squad 7"
   }
   m_aSRFrequencies {
    "2-1"
   }
   m_aLRFrequencies {
    "2PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D886C94CE725}" {
   m_aGroupNames {
    "2-4"
    "Squad 8"
   }
   m_aSRFrequencies {
    "2-1"
   }
   m_aLRFrequencies {
    "2PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D8866EA79604}" {
   m_aGroupNames {
    "3PLT"
    "3rd Platoon"
   }
   m_aSRFrequencies {
    "3PLT SR"
   }
   m_aLRFrequencies {
    "COY"
    "3PLT"
    "3PLT ARMOR"
   }
  }
  CVON_GroupFrequencyContainer "{6642D88668C0259B}" {
   m_aGroupNames {
    "3-1"
    "Squad 9"
   }
   m_aSRFrequencies {
    "3-1"
   }
   m_aLRFrequencies {
    "3PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D88656F4011F}" {
   m_aGroupNames {
    "3-2"
    "Squad 10"
   }
   m_aSRFrequencies {
    "3-2"
   }
   m_aLRFrequencies {
    "3PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D88651A750C0}" {
   m_aGroupNames {
    "3-3"
    "Squad 11"
   }
   m_aSRFrequencies {
    "3-3"
   }
   m_aLRFrequencies {
    "3PLT"
   }
  }
  CVON_GroupFrequencyContainer "{6642D88650DBC087}" {
   m_aGroupNames {
    "3-4"
    "Squad 12"
   }
   m_aSRFrequencies {
    "3-4"
   }
   m_aLRFrequencies {
    "3PLT"
   }
  }
  CVON_GroupFrequencyContainer "{66435A4D8F37EFF1}" {
   m_aGroupNames {
    "Medics"
    "MEDIC"
   }
   m_aSRFrequencies {
    "MEDIC SR"
   }
   m_aLRFrequencies {
    "MEDIC"
    "COY"
   }
  }
 }
}